"""emails provenance + hardened password reset codes

Revision ID: b7c1f2a9d4e0
Revises: 408b15338657
Create Date: 2026-09-10 12:00:00.000000

Adds sender-side provenance to `emails` (who/where queued it) and hardens
`password_reset_tokens` for one-time codes: keyed `code_hash` (replacing the
plaintext `code`), attempt cap, expiry, send-count and cooldown bookkeeping.

Hand-written (not autogenerated): the partial-index/column replacements are
exactly the cases autogenerate gets wrong.
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b7c1f2a9d4e0"
down_revision = "408b15338657"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # --- emails: provenance for the sender-side analytics story ---
    op.add_column("emails", sa.Column("actor_id", sa.BigInteger(), nullable=True))
    op.add_column("emails", sa.Column("source_ip", sa.String(length=45), nullable=True))
    op.add_column("emails", sa.Column("request_id", sa.String(length=64), nullable=True))
    op.add_column("emails", sa.Column("user_agent", sa.String(length=512), nullable=True))
    op.create_index("ix_emails_actor_id", "emails", ["actor_id"], unique=False)
    op.create_index("ix_emails_request_id", "emails", ["request_id"], unique=False)
    # Stats/list date-range queries filter created_at.
    op.create_index("ix_emails_created_at", "emails", ["created_at"], unique=False)

    # --- password_reset_tokens: 4-digit-code hardening ---
    op.add_column(
        "password_reset_tokens",
        sa.Column("code_hash", sa.String(length=255), nullable=True, comment="HMAC-SHA256 of the one-time code"),
    )
    op.add_column(
        "password_reset_tokens",
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "password_reset_tokens",
        sa.Column("max_attempts", sa.Integer(), server_default="5", nullable=False),
    )
    op.add_column(
        "password_reset_tokens",
        sa.Column("sent_count", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column("password_reset_tokens", sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("password_reset_tokens", sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("password_reset_tokens", sa.Column("request_ip", sa.String(length=45), nullable=True))
    op.add_column("password_reset_tokens", sa.Column("last_sent_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index("ix_password_reset_tokens_expires_at", "password_reset_tokens", ["expires_at"], unique=False)
    # The plaintext code column is replaced by code_hash.
    op.drop_column("password_reset_tokens", "code")


def downgrade() -> None:
    op.add_column("password_reset_tokens", sa.Column("code", sa.String(length=10), nullable=True))
    op.drop_index("ix_password_reset_tokens_expires_at", table_name="password_reset_tokens")
    for column in (
        "last_sent_at",
        "request_ip",
        "consumed_at",
        "expires_at",
        "sent_count",
        "max_attempts",
        "attempts",
        "code_hash",
    ):
        op.drop_column("password_reset_tokens", column)

    op.drop_index("ix_emails_request_id", table_name="emails")
    op.drop_index("ix_emails_actor_id", table_name="emails")
    op.drop_index("ix_emails_created_at", table_name="emails")
    for column in ("user_agent", "request_id", "source_ip", "actor_id"):
        op.drop_column("emails", column)
