"""telemetry table comments (user_live_locations, user_location_pings)

Revision ID: 55ffec3914f1
Revises: fdbf62102e86
Create Date: 2026-09-21 12:54:08.377340
"""
from alembic import op
import sqlalchemy as sa


revision = '55ffec3914f1'
down_revision = 'fdbf62102e86'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'user_live_locations',
        'Last known position per user (hot but isolated from the users row).',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'user_location_pings',
        'Append-only location history; monthly partitions via pg_partman.',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'user_location_pings',
        existing_comment='Append-only location history; monthly partitions via pg_partman.',
        schema=None
    )
    op.drop_table_comment(
        'user_live_locations',
        existing_comment='Last known position per user (hot but isolated from the users row).',
        schema=None
    )
    # ### end Alembic commands ###
