"""Zoho control plane: runs, cursors, quota days, sync events, retention policies

Hand-written (not autogenerated) because:
  * ``zoho_sync_events`` is a natively partitioned table (RANGE on
    ``occurred_at``) with a DEFAULT partition so an insert can never fail for a
    missing day partition; daily partitions are created ahead by the retention
    task (app/modules/zoho/control/retention.py). Native partitioning is used
    instead of pg_partman so the same migration runs on the scratch test image,
    which does not ship pg_partman.
  * the partial unique index on ``zoho_sync_runs`` is the run-exclusion
    guarantee and must be reviewed, not inferred.

Revision ID: d4e5f6a7b8c9
Revises: c3d4e5f6a7b8
Create Date: 2026-09-18
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "d4e5f6a7b8c9"
down_revision: str | None = "c3d4e5f6a7b8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ── zoho_sync_runs ──────────────────────────────────────────────────────
    op.create_table(
        "zoho_sync_runs",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("module", sa.String(64), nullable=False),
        sa.Column("lane", sa.String(32), nullable=False),
        sa.Column("mode", sa.String(24)),
        sa.Column("trigger", sa.String(24), nullable=False),
        sa.Column("status", sa.String(16), nullable=False),
        sa.Column("lease_owner", sa.String(160)),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True)),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True)),
        sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True)),
        sa.Column("pages", sa.Integer(), server_default="0", nullable=False),
        sa.Column("listed", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created", sa.Integer(), server_default="0", nullable=False),
        sa.Column("updated", sa.Integer(), server_default="0", nullable=False),
        sa.Column("skipped", sa.Integer(), server_default="0", nullable=False),
        sa.Column("errors", sa.Integer(), server_default="0", nullable=False),
        sa.Column("soft_deleted", sa.Integer(), server_default="0", nullable=False),
        sa.Column("queued_details", sa.Integer(), server_default="0", nullable=False),
        sa.Column("duration_ms", sa.Integer()),
        sa.Column("stop_reason", sa.String(64)),
        sa.Column("error_category", sa.String(32)),
        sa.Column("error_fingerprint", sa.String(16)),
        sa.Column("error_message", sa.Text()),
        sa.Column("trace_id", sa.String(64)),
        sa.Column("request_id", sa.String(64)),
        sa.Column("requested_by", sa.BigInteger()),
        sa.Column("overrides", postgresql.JSONB()),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_zoho_sync_runs_one_running", "zoho_sync_runs", ["module", "lane"], unique=True,
        postgresql_where=sa.text("status = 'running'"),
    )
    op.create_index("ix_zoho_sync_runs_module_lane_started", "zoho_sync_runs", ["module", "lane", "started_at"])
    op.create_index("ix_zoho_sync_runs_status", "zoho_sync_runs", ["status"])

    # ── zoho_sync_cursors ───────────────────────────────────────────────────
    op.create_table(
        "zoho_sync_cursors",
        sa.Column("module", sa.String(64), nullable=False),
        sa.Column("lane", sa.String(32), nullable=False),
        sa.Column("watermark", sa.DateTime(timezone=True)),
        sa.Column("scan_started_at", sa.DateTime(timezone=True)),
        sa.Column("next_page", sa.Integer(), server_default="1", nullable=False),
        sa.Column("scan_id", postgresql.UUID(as_uuid=True)),
        sa.Column("state", postgresql.JSONB(), server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column("owner_run_id", postgresql.UUID(as_uuid=True)),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("module", "lane"),
    )

    # ── zoho_quota_days ─────────────────────────────────────────────────────
    op.create_table(
        "zoho_quota_days",
        sa.Column("pool", sa.String(32), nullable=False),
        sa.Column("day", sa.String(8), nullable=False),
        sa.Column("used", sa.Integer(), server_default="0", nullable=False),
        sa.Column("used_background", sa.Integer(), server_default="0", nullable=False),
        sa.Column("reserved_peak", sa.Integer(), server_default="0", nullable=False),
        sa.Column("by_priority", postgresql.JSONB(), server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column("state", sa.String(16)),
        sa.Column("exhausted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("state_changes", postgresql.JSONB(), server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column("daily_hard_limit", sa.Integer()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("pool", "day"),
    )

    # ── zoho_sync_events (partitioned) ──────────────────────────────────────
    op.execute(
        """
        CREATE TABLE zoho_sync_events (
            id                      bigint GENERATED ALWAYS AS IDENTITY,
            occurred_at             timestamptz NOT NULL DEFAULT now(),
            module                  varchar(64) NOT NULL,
            local_id                bigint,
            zoho_id                 varchar(64),
            event_type              varchar(32) NOT NULL,
            direction               varchar(8)  NOT NULL,
            source                  varchar(48),
            run_id                  uuid,
            command_id              bigint,
            inbox_id                bigint,
            changed_fields          text[],
            diff                    jsonb,
            zoho_last_modified_time timestamptz,
            actor_user_id           bigint,
            request_id              varchar(64),
            trace_id                varchar(64),
            error_category          varchar(32),
            error_fingerprint       varchar(16),
            message                 text,
            PRIMARY KEY (id, occurred_at)
        ) PARTITION BY RANGE (occurred_at)
        """
    )
    # Catch-all so an insert never fails when a day partition is missing.
    op.execute("CREATE TABLE zoho_sync_events_default PARTITION OF zoho_sync_events DEFAULT")
    op.create_index("ix_zoho_sync_events_module_local", "zoho_sync_events", ["module", "local_id", "occurred_at"])
    op.create_index("ix_zoho_sync_events_module_zoho", "zoho_sync_events", ["module", "zoho_id", "occurred_at"])
    op.create_index("ix_zoho_sync_events_run", "zoho_sync_events", ["run_id"])

    # ── zoho_retention_policies ─────────────────────────────────────────────
    policies = op.create_table(
        "zoho_retention_policies",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("table_name", sa.String(64), nullable=False),
        sa.Column("module", sa.String(64), server_default="*", nullable=False),
        sa.Column("event_class", sa.String(32), server_default="*", nullable=False),
        sa.Column("keep_days", sa.Integer(), nullable=False),
        sa.Column("archive", sa.String(16), server_default="none", nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("updated_by", sa.BigInteger()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("table_name", "module", "event_class", name="uq_zoho_retention_scope"),
    )
    op.bulk_insert(
        policies,
        [
            {"table_name": "zoho_sync_events", "module": "*", "event_class": "*", "keep_days": 90},
            {"table_name": "zoho_sync_events", "module": "*", "event_class": "success", "keep_days": 30},
            {"table_name": "zoho_sync_events", "module": "*", "event_class": "failure", "keep_days": 180},
            {"table_name": "zoho_sync_events", "module": "*", "event_class": "conflict", "keep_days": 365},
            {"table_name": "zoho_sync_events", "module": "*", "event_class": "approval", "keep_days": 2555},
            {"table_name": "zoho_sync_runs", "module": "*", "event_class": "*", "keep_days": 90},
            {"table_name": "zoho_quota_days", "module": "*", "event_class": "*", "keep_days": 400},
        ],
    )


def downgrade() -> None:
    op.drop_table("zoho_retention_policies")
    op.execute("DROP TABLE IF EXISTS zoho_sync_events CASCADE")
    op.drop_table("zoho_quota_days")
    op.drop_table("zoho_sync_cursors")
    op.drop_index("ix_zoho_sync_runs_status", table_name="zoho_sync_runs")
    op.drop_index("ix_zoho_sync_runs_module_lane_started", table_name="zoho_sync_runs")
    op.drop_index("uq_zoho_sync_runs_one_running", table_name="zoho_sync_runs")
    op.drop_table("zoho_sync_runs")
