"""entity_aliases app metadata columns

Revision ID: 83faf3dfb47d
Revises: 55ffec3914f1
Create Date: 2026-09-21 14:15:34.641541
"""
from alembic import op
import sqlalchemy as sa


revision = '83faf3dfb47d'
down_revision = '55ffec3914f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entity_aliases', 'app_version',
               existing_type=sa.VARCHAR(length=32),
               comment='App version that last wrote the row',
               existing_nullable=True,
               schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entity_aliases', 'app_version',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='App version that last wrote the row',
               existing_nullable=True,
               schema='core')
    # ### end Alembic commands ###
