"""zoho sync engine, organizations, tags, documents, media, emails, favorites collections

Revision ID: 408b15338657
Revises: 5e085b3cde6f
Create Date: 2026-07-05 18:25:23.922573
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '408b15338657'
down_revision = '5e085b3cde6f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # zoho_organizations.custom_fields is HSTORE — the compose stack enables
    # the extension at cluster init, but be defensive for other environments.
    op.execute("CREATE EXTENSION IF NOT EXISTS hstore")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('documentable_id', sa.String(length=64), nullable=True),
    sa.Column('documentable_type', sa.String(length=100), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='Bytes'),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('zoho_id', sa.String(length=50), nullable=True),
    sa.Column('folder_id', sa.String(length=50), nullable=True),
    sa.Column('folder_name', sa.String(length=255), nullable=True),
    sa.Column('document_status', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('s3_bucket', sa.String(length=100), nullable=True),
    sa.Column('s3_key', sa.String(length=500), nullable=True),
    sa.Column('s3_version_id', sa.String(length=100), nullable=True),
    sa.Column('s3_region', sa.String(length=50), nullable=True),
    sa.Column('s3_storage_class', sa.String(length=50), nullable=True),
    sa.Column('s3_etag', sa.String(length=100), nullable=True),
    sa.Column('s3_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=True),
    sa.Column('processing_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scanned_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vendor_name', sa.String(length=255), nullable=True),
    sa.Column('scanned_receipt_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extracted_text', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('checksum_md5', sa.String(length=32), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('virus_scanned', sa.Boolean(), nullable=True),
    sa.Column('contains_pii', sa.Boolean(), nullable=True),
    sa.Column('access_permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=True),
    sa.Column('version_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_deleted_at'), 'documents', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_documents_document_status'), 'documents', ['document_status'], unique=False)
    op.create_index(op.f('ix_documents_documentable_id'), 'documents', ['documentable_id'], unique=False)
    op.create_index(op.f('ix_documents_documentable_type'), 'documents', ['documentable_type'], unique=False)
    op.create_index(op.f('ix_documents_file_name'), 'documents', ['file_name'], unique=False)
    op.create_index(op.f('ix_documents_file_type'), 'documents', ['file_type'], unique=False)
    op.create_index('ix_documents_owner', 'documents', ['documentable_type', 'documentable_id'], unique=False)
    op.create_index(op.f('ix_documents_processing_status'), 'documents', ['processing_status'], unique=False)
    op.create_index(op.f('ix_documents_s3_key'), 'documents', ['s3_key'], unique=False)
    op.create_index(op.f('ix_documents_vendor_name'), 'documents', ['vendor_name'], unique=False)
    op.create_index('uq_documents_zoho_id_live', 'documents', ['zoho_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL AND zoho_id IS NOT NULL'))
    op.create_table('emails',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('emailable_id', sa.String(length=64), nullable=True),
    sa.Column('emailable_type', sa.String(length=100), nullable=True),
    sa.Column('email_to', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('email_cc', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('email_bcc', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('all_recipients', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Deduped union for fast lookups'),
    sa.Column('email_from', sa.String(length=255), nullable=False),
    sa.Column('email_from_name', sa.String(length=255), nullable=True),
    sa.Column('reply_to', sa.String(length=255), nullable=True),
    sa.Column('return_path', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=998), nullable=True),
    sa.Column('preheader', sa.String(length=255), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('body_type', sa.String(length=20), nullable=True),
    sa.Column('template_id', sa.String(length=100), nullable=True),
    sa.Column('template_name', sa.String(length=255), nullable=True),
    sa.Column('template_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=True),
    sa.Column('campaign_id', sa.String(length=100), nullable=True),
    sa.Column('batch_id', sa.String(length=100), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('status_message', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('status_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_bulk', sa.Boolean(), nullable=True),
    sa.Column('is_transactional', sa.Boolean(), nullable=True),
    sa.Column('track_opens', sa.Boolean(), nullable=True),
    sa.Column('track_clicks', sa.Boolean(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('provider_message_id', sa.String(length=100), nullable=True),
    sa.Column('provider_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_clicked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('open_count', sa.Integer(), nullable=True),
    sa.Column('click_count', sa.Integer(), nullable=True),
    sa.Column('bounce_type', sa.String(length=20), nullable=True, comment='soft | hard'),
    sa.Column('spam_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emails_batch_id'), 'emails', ['batch_id'], unique=False)
    op.create_index(op.f('ix_emails_campaign_id'), 'emails', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_emails_deleted_at'), 'emails', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_emails_email_from'), 'emails', ['email_from'], unique=False)
    op.create_index(op.f('ix_emails_emailable_id'), 'emails', ['emailable_id'], unique=False)
    op.create_index(op.f('ix_emails_emailable_type'), 'emails', ['emailable_type'], unique=False)
    op.create_index(op.f('ix_emails_next_retry_at'), 'emails', ['next_retry_at'], unique=False)
    op.create_index(op.f('ix_emails_provider_message_id'), 'emails', ['provider_message_id'], unique=False)
    op.create_index(op.f('ix_emails_scheduled_at'), 'emails', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_emails_status'), 'emails', ['status'], unique=False)
    op.create_index(op.f('ix_emails_uuid'), 'emails', ['uuid'], unique=True)
    op.create_table('media',
    sa.Column('uuid', sa.UUID(), nullable=False, comment='Public identifier'),
    sa.Column('model_type', sa.String(length=100), nullable=False),
    sa.Column('model_id', sa.String(length=64), nullable=False),
    sa.Column('collection_name', sa.String(length=100), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='Stored (disk) file name'),
    sa.Column('original_name', sa.String(length=255), nullable=True, comment='Client-supplied name'),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('disk', sa.String(length=20), nullable=True, comment='Storage driver: local | s3'),
    sa.Column('size', sa.Integer(), nullable=True, comment='Bytes'),
    sa.Column('conversions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('custom_properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('order_column', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_media_collection_name'), 'media', ['collection_name'], unique=False)
    op.create_index(op.f('ix_media_deleted_at'), 'media', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_media_model_id'), 'media', ['model_id'], unique=False)
    op.create_index(op.f('ix_media_model_type'), 'media', ['model_type'], unique=False)
    op.create_index('ix_media_owner', 'media', ['model_type', 'model_id', 'collection_name'], unique=False)
    op.create_table('tags',
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Locale map, e.g. {"en": "Urgent"}'),
    sa.Column('slug', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Locale map, e.g. {"en": "urgent"}'),
    sa.Column('type', sa.String(length=100), nullable=True, comment="Namespace, e.g. 'badges'"),
    sa.Column('order_column', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_type'), 'tags', ['type'], unique=False)
    op.create_table('zoho_organizations',
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('is_default_org', sa.Boolean(), nullable=True),
    sa.Column('is_org_active', sa.Boolean(), nullable=True),
    sa.Column('user_role', sa.String(length=100), nullable=True),
    sa.Column('user_status', sa.String(length=50), nullable=True),
    sa.Column('account_created_date', sa.Date(), nullable=True),
    sa.Column('industry_type', sa.String(length=100), nullable=True),
    sa.Column('industry_size', sa.String(length=100), nullable=True),
    sa.Column('language_code', sa.String(length=10), nullable=True),
    sa.Column('time_zone', sa.String(length=64), nullable=True),
    sa.Column('date_format', sa.String(length=50), nullable=True),
    sa.Column('field_separator', sa.String(length=10), nullable=True),
    sa.Column('fiscal_year_start_month', sa.Integer(), nullable=True),
    sa.Column('tax_group_enabled', sa.Boolean(), nullable=True),
    sa.Column('currency_id', sa.String(length=50), nullable=True),
    sa.Column('currency_code', sa.String(length=10), nullable=True),
    sa.Column('currency_symbol', sa.String(length=10), nullable=True),
    sa.Column('currency_format', sa.String(length=50), nullable=True),
    sa.Column('price_precision', sa.Integer(), nullable=True),
    sa.Column('address_street1', sa.String(length=255), nullable=True),
    sa.Column('address_street2', sa.String(length=255), nullable=True),
    sa.Column('address_city', sa.String(length=100), nullable=True),
    sa.Column('address_state', sa.String(length=100), nullable=True),
    sa.Column('address_country', sa.String(length=100), nullable=True),
    sa.Column('address_zip', sa.String(length=20), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('zoho_id', sa.String(length=50), nullable=True, comment='Zoho primary key; NULL until first outbound push succeeds'),
    sa.Column('code', sa.String(length=50), nullable=True, comment="Short human reference (unique when set; NULLs don't collide)"),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_status', sa.String(length=20), nullable=True),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('sync_attempt_count', sa.Integer(), nullable=True),
    sa.Column('sync_logs', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Rolling per-row journal of sync events'),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_promoted', sa.Boolean(), nullable=True),
    sa.Column('is_sponsored', sa.Boolean(), nullable=True),
    sa.Column('is_partnered', sa.Boolean(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('show_in_menu', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('menu_order', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Flexible extension data'),
    sa.Column('document_id', sa.String(length=50), nullable=True, comment='Optional link into the documents module'),
    sa.Column('custom_fields', postgresql.HSTORE(text_type=sa.Text()), nullable=True, comment='Zoho custom fields flattened to text (raw array in zoho_raw)'),
    sa.Column('zoho_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Full untouched Zoho document'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_zoho_organizations_deleted_at'), 'zoho_organizations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_zoho_organizations_email'), 'zoho_organizations', ['email'], unique=False)
    op.create_index(op.f('ix_zoho_organizations_name'), 'zoho_organizations', ['name'], unique=False)
    op.create_index(op.f('ix_zoho_organizations_sync_status'), 'zoho_organizations', ['sync_status'], unique=False)
    op.create_index(op.f('ix_zoho_organizations_zoho_id'), 'zoho_organizations', ['zoho_id'], unique=False)
    op.create_index('uq_zoho_organizations_zoho_id_live', 'zoho_organizations', ['zoho_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL AND zoho_id IS NOT NULL'))
    op.create_table('zoho_queue_logs',
    sa.Column('module_name', sa.String(length=64), nullable=False),
    sa.Column('zoho_id', sa.String(length=50), nullable=True),
    sa.Column('local_id', sa.String(length=64), nullable=True),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='queued | processing | success | failed | skipped'),
    sa.Column('attempt', sa.Integer(), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('celery_task_id', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Operation context (params, diff, response snippets)'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zoho_queue_logs_local_id'), 'zoho_queue_logs', ['local_id'], unique=False)
    op.create_index(op.f('ix_zoho_queue_logs_module_name'), 'zoho_queue_logs', ['module_name'], unique=False)
    op.create_index('ix_zoho_queue_logs_module_status', 'zoho_queue_logs', ['module_name', 'status'], unique=False)
    op.create_index('ix_zoho_queue_logs_module_zoho_id', 'zoho_queue_logs', ['module_name', 'zoho_id'], unique=False)
    op.create_index(op.f('ix_zoho_queue_logs_status'), 'zoho_queue_logs', ['status'], unique=False)
    op.create_index(op.f('ix_zoho_queue_logs_zoho_id'), 'zoho_queue_logs', ['zoho_id'], unique=False)
    op.create_table('zoho_sync_stats',
    sa.Column('module_name', sa.String(length=64), nullable=False),
    sa.Column('last_sync_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_full_sync_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_incremental_cursor', sa.String(length=64), nullable=True, comment='Max last_modified_time seen; start of the next incremental window'),
    sa.Column('last_zoho_id_synced', sa.String(length=50), nullable=True),
    sa.Column('total_records_synced', sa.BigInteger(), nullable=True),
    sa.Column('records_created', sa.BigInteger(), nullable=True),
    sa.Column('records_updated', sa.BigInteger(), nullable=True),
    sa.Column('skipped_records', sa.BigInteger(), nullable=True),
    sa.Column('error_count', sa.BigInteger(), nullable=True),
    sa.Column('run_count', sa.BigInteger(), nullable=True),
    sa.Column('last_run_status', sa.String(length=20), nullable=True, comment='success | partial | failed | running'),
    sa.Column('last_run_mode', sa.String(length=20), nullable=True, comment='full | incremental | index'),
    sa.Column('last_run_duration_ms', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zoho_sync_stats_module_name'), 'zoho_sync_stats', ['module_name'], unique=True)
    op.create_table('email_events',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('email_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('event_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True, comment='Clicked URL'),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('provider_event_id', sa.String(length=100), nullable=True),
    sa.Column('provider_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_email_events_email_id'), 'email_events', ['email_id'], unique=False)
    op.create_index(op.f('ix_email_events_event_at'), 'email_events', ['event_at'], unique=False)
    op.create_index(op.f('ix_email_events_event_type'), 'email_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_email_events_provider_event_id'), 'email_events', ['provider_event_id'], unique=False)
    op.create_table('email_links',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('email_id', sa.BigInteger(), nullable=False),
    sa.Column('original_url', sa.String(length=2048), nullable=False),
    sa.Column('link_hash', sa.String(length=128), nullable=True),
    sa.Column('click_count', sa.Integer(), nullable=True),
    sa.Column('unique_clicks', sa.Integer(), nullable=True),
    sa.Column('first_clicked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_clicked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_email_links_email_id'), 'email_links', ['email_id'], unique=False)
    op.create_index(op.f('ix_email_links_link_hash'), 'email_links', ['link_hash'], unique=False)
    op.create_table('taggables',
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.Column('taggable_id', sa.String(length=64), nullable=False),
    sa.Column('taggable_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tag_id', 'taggable_id', 'taggable_type')
    )
    op.create_index(op.f('ix_taggables_taggable_id'), 'taggables', ['taggable_id'], unique=False)
    op.create_index(op.f('ix_taggables_taggable_type'), 'taggables', ['taggable_type'], unique=False)
    op.add_column('favorites', sa.Column('collection_name', sa.String(length=100), server_default='default', nullable=False))
    op.drop_constraint(op.f('uq_favorite_user_target'), 'favorites', type_='unique')
    op.create_unique_constraint('uq_favorite_user_target', 'favorites', ['user_id', 'favoritable_type', 'favoritable_id', 'collection_name'])
    op.create_index(op.f('ix_favorites_collection_name'), 'favorites', ['collection_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favorites_collection_name'), table_name='favorites')
    op.drop_constraint('uq_favorite_user_target', 'favorites', type_='unique')
    op.create_unique_constraint(op.f('uq_favorite_user_target'), 'favorites', ['user_id', 'favoritable_type', 'favoritable_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('favorites', 'collection_name')
    op.drop_index(op.f('ix_taggables_taggable_type'), table_name='taggables')
    op.drop_index(op.f('ix_taggables_taggable_id'), table_name='taggables')
    op.drop_table('taggables')
    op.drop_index(op.f('ix_email_links_link_hash'), table_name='email_links')
    op.drop_index(op.f('ix_email_links_email_id'), table_name='email_links')
    op.drop_table('email_links')
    op.drop_index(op.f('ix_email_events_provider_event_id'), table_name='email_events')
    op.drop_index(op.f('ix_email_events_event_type'), table_name='email_events')
    op.drop_index(op.f('ix_email_events_event_at'), table_name='email_events')
    op.drop_index(op.f('ix_email_events_email_id'), table_name='email_events')
    op.drop_table('email_events')
    op.drop_index(op.f('ix_zoho_sync_stats_module_name'), table_name='zoho_sync_stats')
    op.drop_table('zoho_sync_stats')
    op.drop_index(op.f('ix_zoho_queue_logs_zoho_id'), table_name='zoho_queue_logs')
    op.drop_index(op.f('ix_zoho_queue_logs_status'), table_name='zoho_queue_logs')
    op.drop_index('ix_zoho_queue_logs_module_zoho_id', table_name='zoho_queue_logs')
    op.drop_index('ix_zoho_queue_logs_module_status', table_name='zoho_queue_logs')
    op.drop_index(op.f('ix_zoho_queue_logs_module_name'), table_name='zoho_queue_logs')
    op.drop_index(op.f('ix_zoho_queue_logs_local_id'), table_name='zoho_queue_logs')
    op.drop_table('zoho_queue_logs')
    op.drop_index('uq_zoho_organizations_zoho_id_live', table_name='zoho_organizations', postgresql_where=sa.text('deleted_at IS NULL AND zoho_id IS NOT NULL'))
    op.drop_index(op.f('ix_zoho_organizations_zoho_id'), table_name='zoho_organizations')
    op.drop_index(op.f('ix_zoho_organizations_sync_status'), table_name='zoho_organizations')
    op.drop_index(op.f('ix_zoho_organizations_name'), table_name='zoho_organizations')
    op.drop_index(op.f('ix_zoho_organizations_email'), table_name='zoho_organizations')
    op.drop_index(op.f('ix_zoho_organizations_deleted_at'), table_name='zoho_organizations')
    op.drop_table('zoho_organizations')
    op.drop_index(op.f('ix_tags_type'), table_name='tags')
    op.drop_table('tags')
    op.drop_index('ix_media_owner', table_name='media')
    op.drop_index(op.f('ix_media_model_type'), table_name='media')
    op.drop_index(op.f('ix_media_model_id'), table_name='media')
    op.drop_index(op.f('ix_media_deleted_at'), table_name='media')
    op.drop_index(op.f('ix_media_collection_name'), table_name='media')
    op.drop_table('media')
    op.drop_index(op.f('ix_emails_uuid'), table_name='emails')
    op.drop_index(op.f('ix_emails_status'), table_name='emails')
    op.drop_index(op.f('ix_emails_scheduled_at'), table_name='emails')
    op.drop_index(op.f('ix_emails_provider_message_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_next_retry_at'), table_name='emails')
    op.drop_index(op.f('ix_emails_emailable_type'), table_name='emails')
    op.drop_index(op.f('ix_emails_emailable_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_email_from'), table_name='emails')
    op.drop_index(op.f('ix_emails_deleted_at'), table_name='emails')
    op.drop_index(op.f('ix_emails_campaign_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_batch_id'), table_name='emails')
    op.drop_table('emails')
    op.drop_index('uq_documents_zoho_id_live', table_name='documents', postgresql_where=sa.text('deleted_at IS NULL AND zoho_id IS NOT NULL'))
    op.drop_index(op.f('ix_documents_vendor_name'), table_name='documents')
    op.drop_index(op.f('ix_documents_s3_key'), table_name='documents')
    op.drop_index(op.f('ix_documents_processing_status'), table_name='documents')
    op.drop_index('ix_documents_owner', table_name='documents')
    op.drop_index(op.f('ix_documents_file_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_file_name'), table_name='documents')
    op.drop_index(op.f('ix_documents_documentable_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_documentable_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_deleted_at'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
