"""Location hub — schema ``geo``: places, the address book, geofences.

Creates six tables (docs/geo/README.md):

    geo.admin_boundaries    administrative reference areas (global)
    geo.geocode_api_calls   every external geo-API payload, once
    geo.places              THE canonical physical place
    geo.geofences           zones with an entry / exit / dwell policy
    geo.place_links         any entity ↔ a place — the address book
    geo.place_relationships place ↔ place, with per-mode routing metrics

Extensions required, created here if missing:

    postgis      geography columns and the GiST indexes over them
    pg_trgm      "type three letters of the street" search
    btree_gist   the ``place_links_no_overlap`` EXCLUDE constraint mixes
                 equality on scalars with range overlap, which plain GiST
                 cannot index

Additive and fully reversible: it creates a new schema and touches no
existing table.

Revision ID: 4f2f2a8c7898
Revises: 7c2e91d4b0a8
Create Date: 2026-09-20
"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography
from sqlalchemy.dialects import postgresql

revision = '4f2f2a8c7898'
down_revision = '7c2e91d4b0a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS geo")
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('admin_boundaries',
    sa.Column('level', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Canonical English name'),
    sa.Column('name_local', sa.String(length=255), nullable=True, comment='Vernacular name (e.g. पुणे)'),
    sa.Column('alt_names', postgresql.ARRAY(sa.Text()), nullable=True, comment='Alternative spellings — fuzzy address matching'),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('depth', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('lgd_code', sa.String(length=32), nullable=True, comment='Local Government Directory code'),
    sa.Column('census_code', sa.String(length=32), nullable=True, comment='Census of India code'),
    sa.Column('state_code', sa.String(length=10), nullable=True, comment='MH / KA / DL …'),
    sa.Column('geoname_id', sa.String(length=32), nullable=True),
    sa.Column('iso_code', sa.String(length=16), nullable=True, comment='ISO 3166 code, where one exists'),
    sa.Column('pincode', sa.String(length=16), nullable=True, comment="Set when level = 'pincode'"),
    sa.Column('centroid', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True, comment='Representative point — cheap enough to read on every address form'),
    sa.Column('boundary', Geography(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True, comment='Authoritative polygon; ONE copy platform-wide'),
    sa.Column('timezone', sa.String(length=64), nullable=True, comment='IANA timezone of the area'),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False, comment='Population, data source, vintage …'),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='users.id of the creator (NULL = system)'),
    sa.Column('created_by_name', sa.String(length=255), nullable=True, comment='Creator display name at the time'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='users.id of the last updater'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('row_version', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='Optimistic-lock counter (incremented on every update)'),
    sa.Column('app_version', sa.String(length=32), nullable=True, comment='App version that last wrote the row'),
    sa.Column('app_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True, comment='users.id who deleted it'),
    sa.Column('deleted_reason', sa.Text(), nullable=True, comment='Why it was deleted'),
    sa.CheckConstraint("level IN ('country','state','district','taluka','city','locality','pincode','constituency','sub_constituency','assembly_constituency','parliamentary_constituency')", name='chk_admin_boundary_level'),
    sa.CheckConstraint("path LIKE '/%' AND path LIKE '%/'", name='chk_admin_boundary_path'),
    sa.ForeignKeyConstraint(['parent_id'], ['geo.admin_boundaries.id'], name='fk_admin_boundaries_parent', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level', 'path', name='uq_admin_boundaries_level_path'),
    schema='geo'
    )
    op.create_geospatial_index('idx_admin_boundaries_boundary', 'admin_boundaries', ['boundary'], unique=False, schema='geo', postgresql_using='gist', postgresql_ops={})
    op.create_index('ix_admin_boundaries_lgd_code', 'admin_boundaries', ['lgd_code'], unique=False, schema='geo', postgresql_where=sa.text('lgd_code IS NOT NULL'))
    op.create_index('ix_admin_boundaries_name_trgm', 'admin_boundaries', ['name'], unique=False, schema='geo', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index('ix_admin_boundaries_parent', 'admin_boundaries', ['parent_id'], unique=False, schema='geo')
    op.create_index('ix_admin_boundaries_path', 'admin_boundaries', ['path'], unique=False, schema='geo', postgresql_ops={'path': 'text_pattern_ops'})
    op.create_index('ix_admin_boundaries_pincode', 'admin_boundaries', ['pincode'], unique=False, schema='geo', postgresql_where=sa.text('pincode IS NOT NULL'))
    op.create_index(op.f('ix_geo_admin_boundaries_deleted_at'), 'admin_boundaries', ['deleted_at'], unique=False, schema='geo')
    op.create_index(op.f('ix_geo_admin_boundaries_level'), 'admin_boundaries', ['level'], unique=False, schema='geo')
    op.create_index(op.f('ix_geo_admin_boundaries_status'), 'admin_boundaries', ['status'], unique=False, schema='geo')
    op.create_index(op.f('ix_geo_admin_boundaries_uuid'), 'admin_boundaries', ['uuid'], unique=True, schema='geo')
    op.create_table('geocode_api_calls',
    sa.Column('provider', sa.String(length=32), nullable=False, comment='google / mapmyindia / …'),
    sa.Column('api_type', sa.String(length=32), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False, comment='sha256 of the normalized request params — the cache key'),
    sa.Column('request_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Normalized request parameters'),
    sa.Column('response_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='THE untouched provider payload (the only copy platform-wide)'),
    sa.Column('response_status', sa.String(length=64), nullable=True, comment='Provider status: OK / ZERO_RESULTS / OVER_QUERY_LIMIT …'),
    sa.Column('http_status', sa.SmallInteger(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost_units', sa.Numeric(precision=10, scale=4), nullable=True, comment='Billing units consumed — spend tracking per tenant'),
    sa.Column('resolved_place_id', sa.BigInteger(), nullable=True, comment='The place this call resolved to, if any'),
    sa.Column('requested_by', sa.BigInteger(), nullable=True, comment='users.id that triggered the call (NULL = system)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment="End of the provider's cache window; the purge job sweeps on this"),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='Tenant isolation key'),
    sa.Column('organization_id', sa.BigInteger(), nullable=False, comment='Organization within the tenant (required)'),
    sa.Column('app_version', sa.String(length=32), nullable=True, comment='App version that last wrote the row'),
    sa.Column('app_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.CheckConstraint("api_type IN ('forward_geocode','reverse_geocode','place_details','place_autocomplete','directions','distance_matrix','roads_snap','timezone','address_validation','route_optimization')", name='chk_geocode_call_api_type'),
    sa.CheckConstraint('latency_ms IS NULL OR latency_ms >= 0', name='chk_geocode_call_latency'),
    # fk_geocode_calls_place is added at the end: geo.places does not exist yet
    # (places ↔ geocode_api_calls reference each other — the use_alter cycle).
    sa.ForeignKeyConstraint(['tenant_id', 'organization_id'], ['org_management.organizations.tenant_id', 'org_management.organizations.id'], name='fk_geocode_api_calls_tenant_org', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['org_management.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='geo',
    comment='Raw external geo-API payloads (append-only, TOS-expiring).'
    )
    op.create_index(op.f('ix_geo_geocode_api_calls_tenant_id'), 'geocode_api_calls', ['tenant_id'], unique=False, schema='geo')
    op.create_index(op.f('ix_geo_geocode_api_calls_uuid'), 'geocode_api_calls', ['uuid'], unique=True, schema='geo')
    op.create_index('ix_geocode_api_calls_tenant_org', 'geocode_api_calls', ['tenant_id', 'organization_id'], unique=False, schema='geo')
    op.create_index('ix_geocode_calls_cache', 'geocode_api_calls', ['tenant_id', 'provider', 'api_type', 'request_hash', sa.literal_column('created_at DESC')], unique=False, schema='geo')
    op.create_index('ix_geocode_calls_expiry', 'geocode_api_calls', ['expires_at'], unique=False, schema='geo', postgresql_where=sa.text('expires_at IS NOT NULL'))
    op.create_index('ix_geocode_calls_place', 'geocode_api_calls', ['resolved_place_id'], unique=False, schema='geo', postgresql_where=sa.text('resolved_place_id IS NOT NULL'))
    op.create_geospatial_table('places',
    sa.Column('kind', sa.String(length=32), server_default=sa.text("'address'"), nullable=False, comment='address / customer_site / hub / warehouse / office / landmark / poi'),
    sa.Column('location_name', sa.String(length=255), nullable=True, comment='Display name — "North Hub", "Acme HQ", the Zoho location name'),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment="The organization's primary place of this kind (one, enforced by partial unique)"),
    sa.Column('parent_location_id', sa.BigInteger(), nullable=True, comment='CONTAINMENT only (campus → building → dock). Visit order lives in routes, never here'),
    sa.Column('zoho_id', sa.String(length=50), nullable=True, comment='Zoho location_id when this place mirrors a Zoho location'),
    sa.Column('coordinates', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True, comment='WGS84 point (longitude, latitude). The only stored coordinate'),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), sa.Computed('ST_Y(coordinates::geometry)', persisted=True), nullable=True, comment='GENERATED from coordinates — never written by the application'),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), sa.Computed('ST_X(coordinates::geometry)', persisted=True), nullable=True, comment='GENERATED from coordinates — never written by the application'),
    sa.Column('geohash8', sa.Text(), sa.Computed('ST_GeoHash(coordinates::geometry, 8)', persisted=True), nullable=True, comment='GENERATED 8-char geohash (≈19 m) — the near-duplicate key'),
    sa.Column('attention', sa.String(length=255), nullable=True, comment='Attention / care-of'),
    sa.Column('formatted_address', sa.Text(), nullable=True, comment='Full human-readable address'),
    sa.Column('building_name', sa.String(length=255), nullable=True),
    sa.Column('street', sa.String(length=255), nullable=True),
    sa.Column('street2', sa.String(length=255), nullable=True),
    sa.Column('landmark', sa.String(length=255), nullable=True, comment='Nearby landmark — essential in India'),
    sa.Column('sub_locality', sa.String(length=255), nullable=True, comment='Colony / sector / area'),
    sa.Column('locality', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('taluka', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('state_code', sa.String(length=10), nullable=True, comment='GST state code / ISO subdivision'),
    sa.Column('postal_code', sa.String(length=16), nullable=True),
    sa.Column('country', sa.String(length=100), server_default=sa.text("'India'"), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=True, comment='ISO 3166-1 alpha-2'),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('fax', sa.String(length=50), nullable=True),
    sa.Column('contact_person_name', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True, comment='google / mapmyindia / manual …'),
    sa.Column('provider_place_id', sa.String(length=255), nullable=True, comment='Google place_id etc. — storable indefinitely under the licence'),
    sa.Column('plus_code', sa.String(length=32), nullable=True, comment='Open Location Code'),
    sa.Column('place_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Provider categories ["street_address"]'),
    sa.Column('address_components', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='PARSED components; the raw payload lives once in geocode_api_calls'),
    sa.Column('geocode_call_id', sa.BigInteger(), nullable=True, comment='Provenance: the API call that produced this geocode'),
    sa.Column('viewport', Geography(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True, comment='Provider viewport polygon (replaces four viewport_* decimals)'),
    sa.Column('geocode_confidence', sa.Double(), nullable=True, comment='Provider match confidence 0–1'),
    sa.Column('geocoded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True, comment='IANA timezone at this point'),
    sa.Column('admin_boundary_id', sa.BigInteger(), nullable=True, comment='Smallest containing admin area (resolved once via ST_Covers, then cached)'),
    sa.Column('operating_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='{"mon": [["09:00","18:00"]], …} — structured, not a free-text string'),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False, comment='Business extras (dock height, gate code). App-level data goes in app_metadata'),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='Tenant isolation key'),
    sa.Column('organization_id', sa.BigInteger(), nullable=False, comment='Organization within the tenant (required)'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='users.id of the creator (NULL = system)'),
    sa.Column('created_by_name', sa.String(length=255), nullable=True, comment='Creator display name at the time'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='users.id of the last updater'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('row_version', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='Optimistic-lock counter (incremented on every update)'),
    sa.Column('app_version', sa.String(length=32), nullable=True, comment='App version that last wrote the row'),
    sa.Column('app_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('verification_status', sa.String(length=20), server_default=sa.text("'unverified'"), nullable=False, comment='unverified / geocoded_only / field_verified / disputed (tables CHECK their own set)'),
    sa.Column('verification_method', sa.String(length=50), nullable=True, comment='How it was verified (geocode, field_visit, utility_bill, otp, …)'),
    sa.Column('verification_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Evidence: file refs, provider response ids, signatures'),
    sa.Column('verified_by', sa.BigInteger(), nullable=True, comment='users.id of the verifier (NULL = system)'),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivation_reason', sa.Text(), nullable=True),
    sa.Column('deactivated_by', sa.BigInteger(), nullable=True, comment='users.id who deactivated it'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True, comment='users.id who deleted it'),
    sa.Column('deleted_reason', sa.Text(), nullable=True, comment='Why it was deleted'),
    sa.CheckConstraint("kind IN ('address','customer_site','hub','warehouse','office','landmark','poi')", name='chk_place_kind'),
    sa.CheckConstraint("status IN ('active','archived','invalid')", name='chk_place_status'),
    sa.CheckConstraint("verification_status IN ('unverified','geocoded_only','field_verified','disputed')", name='chk_place_verification_status'),
    sa.CheckConstraint('geocode_confidence IS NULL OR (geocode_confidence >= 0 AND geocode_confidence <= 1)', name='chk_place_geocode_confidence'),
    sa.CheckConstraint('parent_location_id IS NULL OR parent_location_id <> id', name='chk_place_not_own_parent'),
    sa.ForeignKeyConstraint(['admin_boundary_id'], ['geo.admin_boundaries.id'], name='fk_places_admin_boundary', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['geocode_call_id'], ['geo.geocode_api_calls.id'], name='fk_places_geocode_call', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['tenant_id', 'organization_id'], ['org_management.organizations.tenant_id', 'org_management.organizations.id'], name='fk_places_tenant_org', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'parent_location_id'], ['geo.places.tenant_id', 'geo.places.id'], name='fk_places_parent_location', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['org_management.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_places_tenant_id'),
    schema='geo'
    )
    op.create_geospatial_index('idx_places_coordinates', 'places', ['coordinates'], unique=False, schema='geo', postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_geo_places_deleted_at'), 'places', ['deleted_at'], unique=False, schema='geo')
    op.create_index(op.f('ix_geo_places_kind'), 'places', ['kind'], unique=False, schema='geo')
    op.create_index(op.f('ix_geo_places_status'), 'places', ['status'], unique=False, schema='geo')
    op.create_index(op.f('ix_geo_places_tenant_id'), 'places', ['tenant_id'], unique=False, schema='geo')
    op.create_index(op.f('ix_geo_places_uuid'), 'places', ['uuid'], unique=True, schema='geo')
    op.create_index(op.f('ix_geo_places_verification_status'), 'places', ['verification_status'], unique=False, schema='geo')
    op.create_index('ix_places_admin_boundary', 'places', ['admin_boundary_id'], unique=False, schema='geo', postgresql_where=sa.text('admin_boundary_id IS NOT NULL'))
    op.create_index('ix_places_custom_attr', 'places', ['custom_attributes'], unique=False, schema='geo', postgresql_using='gin')
    op.create_index('ix_places_geohash', 'places', ['tenant_id', 'geohash8'], unique=False, schema='geo', postgresql_where=sa.text('geohash8 IS NOT NULL AND deleted_at IS NULL'))
    op.create_index('ix_places_name_trgm', 'places', ['location_name'], unique=False, schema='geo', postgresql_using='gin', postgresql_ops={'location_name': 'gin_trgm_ops'})
    op.create_index('ix_places_parent_location', 'places', ['tenant_id', 'parent_location_id'], unique=False, schema='geo', postgresql_where=sa.text('parent_location_id IS NOT NULL'))
    op.create_index('ix_places_postal_code', 'places', ['tenant_id', 'postal_code'], unique=False, schema='geo', postgresql_where=sa.text('postal_code IS NOT NULL AND deleted_at IS NULL'))
    op.create_index('ix_places_search_trgm', 'places', ['formatted_address'], unique=False, schema='geo', postgresql_using='gin', postgresql_ops={'formatted_address': 'gin_trgm_ops'})
    op.create_index('ix_places_tenant_org', 'places', ['tenant_id', 'organization_id'], unique=False, schema='geo')
    op.create_index('uq_places_primary_per_kind', 'places', ['tenant_id', 'organization_id', 'kind'], unique=True, schema='geo', postgresql_where=sa.text('is_primary AND deleted_at IS NULL'))
    op.create_index('uq_places_provider_place_live', 'places', ['tenant_id', 'provider', 'provider_place_id'], unique=True, schema='geo', postgresql_where=sa.text('deleted_at IS NULL AND provider_place_id IS NOT NULL'))
    op.create_index('uq_places_zoho_id_live', 'places', ['tenant_id', 'zoho_id'], unique=True, schema='geo', postgresql_where=sa.text('deleted_at IS NULL AND zoho_id IS NOT NULL'))
    op.create_geospatial_table('geofences',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('fence_type', sa.String(length=32), nullable=False),
    sa.Column('place_id', sa.BigInteger(), nullable=True, comment='The place this fence guards (fence_type = place_radius)'),
    sa.Column('boundary', Geography(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True, comment='Polygon fence (preferred)'),
    sa.Column('center', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True, comment='Circle-fence centre'),
    sa.Column('radius_m', sa.Double(), nullable=True, comment='Circle-fence radius in metres'),
    sa.Column('dwell_threshold_s', sa.Integer(), server_default=sa.text('60'), nullable=False, comment='Seconds a fix must stay inside before anything fires (jitter guard)'),
    sa.Column('speed_limit_kmh', sa.Double(), nullable=True, comment='Max speed inside the zone'),
    sa.Column('entry_alert', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('exit_alert', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True, comment="['high_risk','warehouse']"),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='Tenant isolation key'),
    sa.Column('organization_id', sa.BigInteger(), nullable=False, comment='Organization within the tenant (required)'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='users.id of the creator (NULL = system)'),
    sa.Column('created_by_name', sa.String(length=255), nullable=True, comment='Creator display name at the time'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='users.id of the last updater'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('row_version', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='Optimistic-lock counter (incremented on every update)'),
    sa.Column('app_version', sa.String(length=32), nullable=True, comment='App version that last wrote the row'),
    sa.Column('app_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deactivation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivation_reason', sa.Text(), nullable=True),
    sa.Column('deactivated_by', sa.BigInteger(), nullable=True, comment='users.id who deactivated it'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True, comment='users.id who deleted it'),
    sa.Column('deleted_reason', sa.Text(), nullable=True, comment='Why it was deleted'),
    sa.CheckConstraint("fence_type IN ('place_radius','hub_zone','beat_area','restricted','custom')", name='chk_geofence_type'),
    sa.CheckConstraint("status IN ('active','suspended','archived')", name='chk_geofence_status'),
    sa.CheckConstraint('boundary IS NOT NULL OR (center IS NOT NULL AND radius_m IS NOT NULL)', name='chk_geofence_shape_present'),
    sa.CheckConstraint('dwell_threshold_s >= 0', name='chk_geofence_dwell_nonnegative'),
    sa.CheckConstraint('radius_m IS NULL OR radius_m > 0', name='chk_geofence_radius_positive'),
    sa.CheckConstraint('valid_to IS NULL OR valid_from IS NULL OR valid_to > valid_from', name='chk_geofence_validity'),
    sa.ForeignKeyConstraint(['place_id'], ['geo.places.id'], name='fk_geofences_place', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'organization_id'], ['org_management.organizations.tenant_id', 'org_management.organizations.id'], name='fk_geofences_tenant_org', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['org_management.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='geo'
    )
    op.create_geospatial_index('idx_geofences_boundary', 'geofences', ['boundary'], unique=False, schema='geo', postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_geofences_center', 'geofences', ['center'], unique=False, schema='geo', postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_geo_geofences_deleted_at'), 'geofences', ['deleted_at'], unique=False, schema='geo')
    op.create_index(op.f('ix_geo_geofences_status'), 'geofences', ['status'], unique=False, schema='geo')
    op.create_index(op.f('ix_geo_geofences_tenant_id'), 'geofences', ['tenant_id'], unique=False, schema='geo')
    op.create_index(op.f('ix_geo_geofences_uuid'), 'geofences', ['uuid'], unique=True, schema='geo')
    op.create_index('ix_geofences_evaluated', 'geofences', ['tenant_id', 'fence_type'], unique=False, schema='geo', postgresql_where=sa.text("status = 'active' AND deleted_at IS NULL"))
    op.create_index('ix_geofences_place', 'geofences', ['place_id'], unique=False, schema='geo', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_geofences_tenant_org', 'geofences', ['tenant_id', 'organization_id'], unique=False, schema='geo')
    op.create_index('uq_geofences_name_live', 'geofences', ['tenant_id', 'organization_id', 'name'], unique=True, schema='geo', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('place_links',
    sa.Column('place_id', sa.BigInteger(), nullable=False, comment='The place this address points at'),
    sa.Column('owner_type', sa.String(length=50), nullable=False, comment='Owning entity class — WHO owns the link'),
    sa.Column('owner_id', sa.BigInteger(), nullable=False, comment='Owning entity id'),
    sa.Column('link_type', sa.String(length=20), server_default=sa.text("'primary'"), nullable=False, comment='WHAT KIND of address it is for the owner'),
    sa.Column('purpose', sa.String(length=50), server_default=sa.text("''"), nullable=False, comment="Operational use (delivery, invoice, returns). '' = none; NOT NULL so it can key a unique index"),
    sa.Column('label', sa.String(length=100), nullable=True, comment='User-facing label: "Head office", "Factory"'),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('attention', sa.String(length=255), nullable=True, comment='Who to ask for at this place, for this owner'),
    sa.Column('landmark', sa.String(length=255), nullable=True, comment='Courier note overriding the place landmark'),
    sa.Column('delivery_instructions', sa.String(length=500), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True, comment='NULL = still current; an address change closes the old row'),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='The address as printed when it was linked. Set for documents; NULL means the link follows the live place'),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='Tenant isolation key'),
    sa.Column('organization_id', sa.BigInteger(), nullable=False, comment='Organization within the tenant (required)'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='users.id of the creator (NULL = system)'),
    sa.Column('created_by_name', sa.String(length=255), nullable=True, comment='Creator display name at the time'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='users.id of the last updater'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('row_version', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='Optimistic-lock counter (incremented on every update)'),
    sa.Column('app_version', sa.String(length=32), nullable=True, comment='App version that last wrote the row'),
    sa.Column('app_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('verification_status', sa.String(length=20), server_default=sa.text("'unverified'"), nullable=False, comment='unverified / geocoded_only / field_verified / disputed (tables CHECK their own set)'),
    sa.Column('verification_method', sa.String(length=50), nullable=True, comment='How it was verified (geocode, field_visit, utility_bill, otp, …)'),
    sa.Column('verification_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Evidence: file refs, provider response ids, signatures'),
    sa.Column('verified_by', sa.BigInteger(), nullable=True, comment='users.id of the verifier (NULL = system)'),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivation_reason', sa.Text(), nullable=True),
    sa.Column('deactivated_by', sa.BigInteger(), nullable=True, comment='users.id who deactivated it'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True, comment='users.id who deleted it'),
    sa.Column('deleted_reason', sa.Text(), nullable=True, comment='Why it was deleted'),
    postgresql.ExcludeConstraint((sa.column('tenant_id'), '='), (sa.column('owner_type'), '='), (sa.column('owner_id'), '='), (sa.column('link_type'), '='), (sa.text('tstzrange(valid_from, valid_to)'), '&&'), where=sa.text("deleted_at IS NULL AND link_type IN ('current','permanent')"), using='gist', name='place_links_no_overlap'),
    sa.CheckConstraint("link_type IN ('primary','billing','shipping','home','office','site','current','permanent','other')", name='chk_place_link_type'),
    sa.CheckConstraint("owner_type IN ('user','organization','customer','contact_person','vendor','warehouse','zoho_location','invoice','estimate','sales_order','purchase_order','shipment')", name='chk_place_link_owner_type'),
    sa.CheckConstraint("status IN ('active','suspended','archived')", name='chk_place_link_status'),
    sa.CheckConstraint("verification_status IN ('unverified','geocoded_only','field_verified','disputed')", name='chk_place_link_verification_status'),
    sa.CheckConstraint('owner_id > 0', name='chk_place_link_owner_id'),
    sa.CheckConstraint('valid_to IS NULL OR valid_to > valid_from', name='chk_place_link_validity'),
    sa.ForeignKeyConstraint(['tenant_id', 'organization_id'], ['org_management.organizations.tenant_id', 'org_management.organizations.id'], name='fk_place_links_tenant_org', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'place_id'], ['geo.places.tenant_id', 'geo.places.id'], name='fk_place_links_tenant_place', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['org_management.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='geo',
    comment='Polymorphic address book: any entity ↔ a canonical place.'
    )
    op.create_index(op.f('ix_geo_place_links_deleted_at'), 'place_links', ['deleted_at'], unique=False, schema='geo')
    op.create_index(op.f('ix_geo_place_links_status'), 'place_links', ['status'], unique=False, schema='geo')
    op.create_index(op.f('ix_geo_place_links_tenant_id'), 'place_links', ['tenant_id'], unique=False, schema='geo')
    op.create_index(op.f('ix_geo_place_links_uuid'), 'place_links', ['uuid'], unique=True, schema='geo')
    op.create_index(op.f('ix_geo_place_links_verification_status'), 'place_links', ['verification_status'], unique=False, schema='geo')
    op.create_index('ix_place_links_owner', 'place_links', ['tenant_id', 'owner_type', 'owner_id', 'link_type'], unique=False, schema='geo', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_place_links_place', 'place_links', ['place_id'], unique=False, schema='geo', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_place_links_tenant_org', 'place_links', ['tenant_id', 'organization_id'], unique=False, schema='geo')
    op.create_index('uq_place_links_dedupe', 'place_links', ['tenant_id', 'owner_type', 'owner_id', 'place_id', 'link_type', 'purpose'], unique=True, schema='geo', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('uq_place_links_one_primary', 'place_links', ['tenant_id', 'owner_type', 'owner_id', 'link_type'], unique=True, schema='geo', postgresql_where=sa.text('is_primary AND valid_to IS NULL AND deleted_at IS NULL'))
    op.create_geospatial_table('place_relationships',
    sa.Column('place_id', sa.BigInteger(), nullable=False, comment='Source place'),
    sa.Column('related_place_id', sa.BigInteger(), nullable=False, comment='Target place'),
    sa.Column('relationship_type', sa.String(length=32), nullable=False),
    sa.Column('is_bidirectional', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment="Metrics apply both ways (replaces a free-text 'direction' column)"),
    sa.Column('transport_mode', sa.String(length=20), server_default=sa.text("'driving'"), nullable=False, comment='Distance and duration differ per mode, so the mode is part of the key'),
    sa.Column('sequence_number', sa.Integer(), nullable=True, comment='Order within a named route'),
    sa.Column('path', Geography(geometry_type='LINESTRING', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True, comment='Route geometry'),
    sa.Column('distance_m', sa.Double(), nullable=True, comment='Computed at write time'),
    sa.Column('duration_s', sa.Double(), nullable=True),
    sa.Column('bearing_deg', sa.Double(), nullable=True),
    sa.Column('routing_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Directions extract: polyline, warnings, tolls'),
    sa.Column('geocode_call_id', sa.BigInteger(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='Tenant isolation key'),
    sa.Column('organization_id', sa.BigInteger(), nullable=False, comment='Organization within the tenant (required)'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='users.id of the creator (NULL = system)'),
    sa.Column('created_by_name', sa.String(length=255), nullable=True, comment='Creator display name at the time'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='users.id of the last updater'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('row_version', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='Optimistic-lock counter (incremented on every update)'),
    sa.Column('app_version', sa.String(length=32), nullable=True, comment='App version that last wrote the row'),
    sa.Column('app_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True, comment='users.id who deleted it'),
    sa.Column('deleted_reason', sa.Text(), nullable=True, comment='Why it was deleted'),
    sa.CheckConstraint("relationship_type IN ('parent_child','route_segment','administrative','geofence_group','spatial_cluster')", name='chk_place_rel_type'),
    sa.CheckConstraint("status IN ('active','suspended','archived')", name='chk_place_rel_status'),
    sa.CheckConstraint("transport_mode IN ('driving','two_wheeler','walking','truck','transit')", name='chk_place_rel_transport'),
    sa.CheckConstraint('bearing_deg IS NULL OR (bearing_deg >= 0 AND bearing_deg < 360)', name='chk_place_rel_bearing'),
    sa.CheckConstraint('distance_m IS NULL OR distance_m >= 0', name='chk_place_rel_distance'),
    sa.CheckConstraint('place_id <> related_place_id', name='chk_place_rel_no_self'),
    sa.ForeignKeyConstraint(['geocode_call_id'], ['geo.geocode_api_calls.id'], name='fk_place_rel_geocode_call', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['tenant_id', 'organization_id'], ['org_management.organizations.tenant_id', 'org_management.organizations.id'], name='fk_place_relationships_tenant_org', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'place_id'], ['geo.places.tenant_id', 'geo.places.id'], name='fk_place_rel_tenant_place', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'related_place_id'], ['geo.places.tenant_id', 'geo.places.id'], name='fk_place_rel_tenant_related', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['org_management.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'place_id', 'related_place_id', 'relationship_type', 'transport_mode', name='uq_place_relationships_pair'),
    schema='geo'
    )
    op.create_geospatial_index('idx_place_relationships_path', 'place_relationships', ['path'], unique=False, schema='geo', postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_geo_place_relationships_deleted_at'), 'place_relationships', ['deleted_at'], unique=False, schema='geo')
    op.create_index(op.f('ix_geo_place_relationships_status'), 'place_relationships', ['status'], unique=False, schema='geo')
    op.create_index(op.f('ix_geo_place_relationships_tenant_id'), 'place_relationships', ['tenant_id'], unique=False, schema='geo')
    op.create_index(op.f('ix_geo_place_relationships_uuid'), 'place_relationships', ['uuid'], unique=True, schema='geo')
    op.create_index('ix_place_rel_from', 'place_relationships', ['tenant_id', 'place_id', 'relationship_type'], unique=False, schema='geo', postgresql_where=sa.text("status = 'active' AND deleted_at IS NULL"))
    op.create_index('ix_place_rel_to', 'place_relationships', ['related_place_id'], unique=False, schema='geo', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_place_relationships_tenant_org', 'place_relationships', ['tenant_id', 'organization_id'], unique=False, schema='geo')
    # ### end Alembic commands ###

    # The use_alter cycle: CREATE TABLE never emits these, so they are added
    # here now that both sides exist.
    op.create_foreign_key(
        'fk_geocode_calls_place', 'geocode_api_calls', 'places', ['resolved_place_id'], ['id'],
        source_schema='geo', referent_schema='geo', ondelete='SET NULL',
    )
    op.create_foreign_key(
        'fk_places_geocode_call', 'places', 'geocode_api_calls', ['geocode_call_id'], ['id'],
        source_schema='geo', referent_schema='geo', ondelete='SET NULL',
    )
    op.create_foreign_key(
        'fk_place_rel_geocode_call', 'place_relationships', 'geocode_api_calls',
        ['geocode_call_id'], ['id'],
        source_schema='geo', referent_schema='geo', ondelete='SET NULL',
    )

    # create_geospatial_table drops the table comment; restore it.
    op.create_table_comment(
        'admin_boundaries',
        'Administrative areas (global reference data — see the module docstring).',
        schema='geo',
    )
    op.create_table_comment(
        'places',
        'Canonical physical places — the only table in the platform storing coordinates.',
        schema='geo',
    )
    op.create_table_comment(
        'geofences', 'Tenant-drawn zones with an entry/exit/dwell policy.', schema='geo',
    )
    op.create_table_comment(
        'place_relationships', 'Place ↔ place relations with per-mode routing metrics.', schema='geo',
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_place_rel_geocode_call', 'place_relationships', schema='geo', type_='foreignkey')
    op.drop_constraint('fk_places_geocode_call', 'places', schema='geo', type_='foreignkey')
    op.drop_constraint('fk_geocode_calls_place', 'geocode_api_calls', schema='geo', type_='foreignkey')
    op.drop_index('ix_place_relationships_tenant_org', table_name='place_relationships', schema='geo')
    op.drop_index('ix_place_rel_to', table_name='place_relationships', schema='geo', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_place_rel_from', table_name='place_relationships', schema='geo', postgresql_where=sa.text("status = 'active' AND deleted_at IS NULL"))
    op.drop_index(op.f('ix_geo_place_relationships_uuid'), table_name='place_relationships', schema='geo')
    op.drop_index(op.f('ix_geo_place_relationships_tenant_id'), table_name='place_relationships', schema='geo')
    op.drop_index(op.f('ix_geo_place_relationships_status'), table_name='place_relationships', schema='geo')
    op.drop_index(op.f('ix_geo_place_relationships_deleted_at'), table_name='place_relationships', schema='geo')
    op.drop_geospatial_index('idx_place_relationships_path', table_name='place_relationships', schema='geo', postgresql_using='gist', column_name='path')
    op.drop_geospatial_table('place_relationships', schema='geo')
    op.drop_index('uq_place_links_one_primary', table_name='place_links', schema='geo', postgresql_where=sa.text('is_primary AND valid_to IS NULL AND deleted_at IS NULL'))
    op.drop_index('uq_place_links_dedupe', table_name='place_links', schema='geo', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_place_links_tenant_org', table_name='place_links', schema='geo')
    op.drop_index('ix_place_links_place', table_name='place_links', schema='geo', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_place_links_owner', table_name='place_links', schema='geo', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_geo_place_links_verification_status'), table_name='place_links', schema='geo')
    op.drop_index(op.f('ix_geo_place_links_uuid'), table_name='place_links', schema='geo')
    op.drop_index(op.f('ix_geo_place_links_tenant_id'), table_name='place_links', schema='geo')
    op.drop_index(op.f('ix_geo_place_links_status'), table_name='place_links', schema='geo')
    op.drop_index(op.f('ix_geo_place_links_deleted_at'), table_name='place_links', schema='geo')
    op.drop_table('place_links', schema='geo')
    op.drop_index('uq_geofences_name_live', table_name='geofences', schema='geo', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_geofences_tenant_org', table_name='geofences', schema='geo')
    op.drop_index('ix_geofences_place', table_name='geofences', schema='geo', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_geofences_evaluated', table_name='geofences', schema='geo', postgresql_where=sa.text("status = 'active' AND deleted_at IS NULL"))
    op.drop_index(op.f('ix_geo_geofences_uuid'), table_name='geofences', schema='geo')
    op.drop_index(op.f('ix_geo_geofences_tenant_id'), table_name='geofences', schema='geo')
    op.drop_index(op.f('ix_geo_geofences_status'), table_name='geofences', schema='geo')
    op.drop_index(op.f('ix_geo_geofences_deleted_at'), table_name='geofences', schema='geo')
    op.drop_geospatial_index('idx_geofences_center', table_name='geofences', schema='geo', postgresql_using='gist', column_name='center')
    op.drop_geospatial_index('idx_geofences_boundary', table_name='geofences', schema='geo', postgresql_using='gist', column_name='boundary')
    op.drop_geospatial_table('geofences', schema='geo')
    op.drop_index('uq_places_zoho_id_live', table_name='places', schema='geo', postgresql_where=sa.text('deleted_at IS NULL AND zoho_id IS NOT NULL'))
    op.drop_index('uq_places_provider_place_live', table_name='places', schema='geo', postgresql_where=sa.text('deleted_at IS NULL AND provider_place_id IS NOT NULL'))
    op.drop_index('uq_places_primary_per_kind', table_name='places', schema='geo', postgresql_where=sa.text('is_primary AND deleted_at IS NULL'))
    op.drop_index('ix_places_tenant_org', table_name='places', schema='geo')
    op.drop_index('ix_places_search_trgm', table_name='places', schema='geo', postgresql_using='gin', postgresql_ops={'formatted_address': 'gin_trgm_ops'})
    op.drop_index('ix_places_postal_code', table_name='places', schema='geo', postgresql_where=sa.text('postal_code IS NOT NULL AND deleted_at IS NULL'))
    op.drop_index('ix_places_parent_location', table_name='places', schema='geo', postgresql_where=sa.text('parent_location_id IS NOT NULL'))
    op.drop_index('ix_places_name_trgm', table_name='places', schema='geo', postgresql_using='gin', postgresql_ops={'location_name': 'gin_trgm_ops'})
    op.drop_index('ix_places_geohash', table_name='places', schema='geo', postgresql_where=sa.text('geohash8 IS NOT NULL AND deleted_at IS NULL'))
    op.drop_index('ix_places_custom_attr', table_name='places', schema='geo', postgresql_using='gin')
    op.drop_index('ix_places_admin_boundary', table_name='places', schema='geo', postgresql_where=sa.text('admin_boundary_id IS NOT NULL'))
    op.drop_index(op.f('ix_geo_places_verification_status'), table_name='places', schema='geo')
    op.drop_index(op.f('ix_geo_places_uuid'), table_name='places', schema='geo')
    op.drop_index(op.f('ix_geo_places_tenant_id'), table_name='places', schema='geo')
    op.drop_index(op.f('ix_geo_places_status'), table_name='places', schema='geo')
    op.drop_index(op.f('ix_geo_places_kind'), table_name='places', schema='geo')
    op.drop_index(op.f('ix_geo_places_deleted_at'), table_name='places', schema='geo')
    op.drop_geospatial_index('idx_places_coordinates', table_name='places', schema='geo', postgresql_using='gist', column_name='coordinates')
    op.drop_geospatial_table('places', schema='geo')
    op.drop_index('ix_geocode_calls_place', table_name='geocode_api_calls', schema='geo', postgresql_where=sa.text('resolved_place_id IS NOT NULL'))
    op.drop_index('ix_geocode_calls_expiry', table_name='geocode_api_calls', schema='geo', postgresql_where=sa.text('expires_at IS NOT NULL'))
    op.drop_index('ix_geocode_calls_cache', table_name='geocode_api_calls', schema='geo')
    op.drop_index('ix_geocode_api_calls_tenant_org', table_name='geocode_api_calls', schema='geo')
    op.drop_index(op.f('ix_geo_geocode_api_calls_uuid'), table_name='geocode_api_calls', schema='geo')
    op.drop_index(op.f('ix_geo_geocode_api_calls_tenant_id'), table_name='geocode_api_calls', schema='geo')
    op.drop_table('geocode_api_calls', schema='geo')
    op.drop_index(op.f('ix_geo_admin_boundaries_uuid'), table_name='admin_boundaries', schema='geo')
    op.drop_index(op.f('ix_geo_admin_boundaries_status'), table_name='admin_boundaries', schema='geo')
    op.drop_index(op.f('ix_geo_admin_boundaries_level'), table_name='admin_boundaries', schema='geo')
    op.drop_index(op.f('ix_geo_admin_boundaries_deleted_at'), table_name='admin_boundaries', schema='geo')
    op.drop_index('ix_admin_boundaries_pincode', table_name='admin_boundaries', schema='geo', postgresql_where=sa.text('pincode IS NOT NULL'))
    op.drop_index('ix_admin_boundaries_path', table_name='admin_boundaries', schema='geo', postgresql_ops={'path': 'text_pattern_ops'})
    op.drop_index('ix_admin_boundaries_parent', table_name='admin_boundaries', schema='geo')
    op.drop_index('ix_admin_boundaries_name_trgm', table_name='admin_boundaries', schema='geo', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index('ix_admin_boundaries_lgd_code', table_name='admin_boundaries', schema='geo', postgresql_where=sa.text('lgd_code IS NOT NULL'))
    op.drop_geospatial_index('idx_admin_boundaries_boundary', table_name='admin_boundaries', schema='geo', postgresql_using='gist', column_name='boundary')
    op.drop_geospatial_table('admin_boundaries', schema='geo')
    # ### end Alembic commands ###
    # The schema is ours alone; the extensions are not, so they stay.
    op.execute("DROP SCHEMA IF EXISTS geo CASCADE")
