"""baseline schema

Revision ID: 5e085b3cde6f
Revises: 
Create Date: 2026-06-18 12:58:20.312620
"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography
from sqlalchemy.dialects import postgresql

revision = '5e085b3cde6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('activity_id', sa.UUID(), nullable=False, comment='Public identifier'),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='success | failure'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('actor_id', sa.BigInteger(), nullable=True, comment='users.id'),
    sa.Column('actor_type', sa.String(length=20), nullable=False, comment='user | system | service'),
    sa.Column('actor_label', sa.String(length=255), nullable=True, comment='email/name snapshot'),
    sa.Column('subject_type', sa.String(length=100), nullable=True),
    sa.Column('subject_id', sa.String(length=64), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activity_action_created', 'activity_logs', ['action', 'created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_action'), 'activity_logs', ['action'], unique=False)
    op.create_index(op.f('ix_activity_logs_activity_id'), 'activity_logs', ['activity_id'], unique=True)
    op.create_index(op.f('ix_activity_logs_actor_id'), 'activity_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_request_id'), 'activity_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_subject_id'), 'activity_logs', ['subject_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_subject_type'), 'activity_logs', ['subject_type'], unique=False)
    op.create_index(op.f('ix_activity_logs_tenant_id'), 'activity_logs', ['tenant_id'], unique=False)
    op.create_index('ix_activity_subject', 'activity_logs', ['subject_type', 'subject_id'], unique=False)
    op.create_index('ix_activity_tenant_created', 'activity_logs', ['tenant_id', 'created_at'], unique=False)
    op.create_table('files',
    sa.Column('file_id', sa.UUID(), nullable=False, comment='Public UUID'),
    sa.Column('fileable_type', sa.String(length=100), nullable=True),
    sa.Column('fileable_id', sa.String(length=50), nullable=True),
    sa.Column('zoho_id', sa.String(length=50), nullable=True),
    sa.Column('folder_id', sa.String(length=50), nullable=True),
    sa.Column('folder_name', sa.String(length=255), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='Size in bytes'),
    sa.Column('document_scan_status', sa.String(length=100), nullable=True),
    sa.Column('scanned_amount', sa.Numeric(precision=15, scale=8), nullable=False),
    sa.Column('vendor_name', sa.String(length=255), nullable=True),
    sa.Column('scanned_receipt_date', sa.Date(), nullable=True),
    sa.Column('s3_bucket', sa.String(length=100), nullable=True),
    sa.Column('s3_key', sa.String(length=500), nullable=True),
    sa.Column('s3_version_id', sa.String(length=100), nullable=True),
    sa.Column('s3_region', sa.String(length=50), nullable=True),
    sa.Column('s3_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('s3_storage_class', sa.String(length=50), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=False),
    sa.Column('checksum_md5', sa.String(length=32), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('virus_scanned', sa.Boolean(), nullable=False),
    sa.Column('virus_scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contains_pii', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('uploaded_by', sa.String(length=255), nullable=True),
    sa.Column('uploaded_by_id', sa.String(length=50), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_created_at_processing_status', 'files', ['created_at', 'processing_status'], unique=False)
    op.create_index('ix_file_type_processing_status', 'files', ['file_type', 'processing_status'], unique=False)
    op.create_index(op.f('ix_files_deleted_at'), 'files', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_files_file_id'), 'files', ['file_id'], unique=True)
    op.create_index(op.f('ix_files_file_name'), 'files', ['file_name'], unique=False)
    op.create_index(op.f('ix_files_file_type'), 'files', ['file_type'], unique=False)
    op.create_index(op.f('ix_files_fileable_id'), 'files', ['fileable_id'], unique=False)
    op.create_index(op.f('ix_files_fileable_type'), 'files', ['fileable_type'], unique=False)
    op.create_index(op.f('ix_files_is_active'), 'files', ['is_active'], unique=False)
    op.create_index(op.f('ix_files_is_verified'), 'files', ['is_verified'], unique=False)
    op.create_index(op.f('ix_files_processing_status'), 'files', ['processing_status'], unique=False)
    op.create_index(op.f('ix_files_s3_bucket'), 'files', ['s3_bucket'], unique=False)
    op.create_index(op.f('ix_files_s3_key'), 'files', ['s3_key'], unique=False)
    op.create_index(op.f('ix_files_tenant_id'), 'files', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_files_uploaded_by'), 'files', ['uploaded_by'], unique=False)
    op.create_index(op.f('ix_files_vendor_name'), 'files', ['vendor_name'], unique=False)
    op.create_index(op.f('ix_files_zoho_id'), 'files', ['zoho_id'], unique=True)
    op.create_table('password_reset_tokens',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('reset_type', sa.String(length=255), nullable=False, comment="'link' or 'code'"),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_geospatial_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('remember_token', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True, comment='Unique username for login or display'),
    sa.Column('salutation', sa.String(length=255), nullable=True, comment="User's salutation (e.g., Mr., Ms., Dr.)"),
    sa.Column('first_name', sa.String(length=255), nullable=True, comment="User's first name"),
    sa.Column('middle_name', sa.String(length=255), nullable=True, comment="User's middle name"),
    sa.Column('last_name', sa.String(length=255), nullable=True, comment="User's last name"),
    sa.Column('phone_verified_at', sa.DateTime(timezone=True), nullable=True, comment="Timestamp when the user's phone number was verified"),
    sa.Column('two_factor_secret', sa.Text(), nullable=True, comment='Encrypted secret key for TOTP-based two-factor authentication'),
    sa.Column('two_factor_recovery_codes', sa.Text(), nullable=True, comment='Encrypted recovery codes for two-factor authentication'),
    sa.Column('two_factor_confirmed_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when two-factor authentication was confirmed/enabled'),
    sa.Column('api_token', sa.String(length=80), nullable=True, comment='Unique token for API authentication'),
    sa.Column('role_id', sa.Integer(), nullable=True, comment='Foreign key referencing the roles table'),
    sa.Column('user_type', sa.String(length=50), nullable=True, comment='Broad classification of the user (e.g., Employee, Customer, Admin)'),
    sa.Column('status', sa.String(length=25), nullable=True, comment='General status indicator (e.g., active, inactive, pending)'),
    sa.Column('user_status', sa.String(length=255), nullable=True, comment='Detailed user status (e.g., active, suspended, onboarding)'),
    sa.Column('status_reason', sa.Text(), nullable=True, comment='Reason for the current user_status'),
    sa.Column('is_deactivated', sa.Boolean(), nullable=True, comment='Flag indicating if the user account is deactivated'),
    sa.Column('deactivation_date', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the user account was deactivated'),
    sa.Column('deactivation_reason', sa.Text(), nullable=True, comment='Reason provided for account deactivation'),
    sa.Column('confirmation_status', sa.SmallInteger(), nullable=True, comment='Confirmation status (0 = Not Confirmed, 1 = Confirmed)'),
    sa.Column('phone', sa.String(length=255), nullable=True, comment='Primary phone number of the user'),
    sa.Column('contact', sa.String(length=50), nullable=True, comment='Alternative or secondary contact number/method'),
    sa.Column('gender', sa.String(length=50), nullable=True, comment="User's gender"),
    sa.Column('date_of_birth', sa.Date(), nullable=True, comment="User's date of birth"),
    sa.Column('is_married', sa.Boolean(), nullable=True, comment='Marital status flag'),
    sa.Column('citizenship', sa.String(length=255), nullable=True, comment="User's citizenship"),
    sa.Column('blood_group', sa.String(length=255), nullable=True, comment="User's blood group"),
    sa.Column('pan', sa.String(length=255), nullable=True, comment="User's Permanent Account Number (PAN)"),
    sa.Column('gstin', sa.String(length=255), nullable=True, comment="User's GST Identification Number (GSTIN)"),
    sa.Column('tax_preference', sa.String(length=255), nullable=True, comment="User's tax preference setting"),
    sa.Column('gst_treatment', sa.String(length=255), nullable=True, comment="User's GST treatment status"),
    sa.Column('languages_known', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON array of languages known by the user'),
    sa.Column('social_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON object containing links to social media profiles'),
    sa.Column('emergency_contact', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON object with emergency contact details'),
    sa.Column('medical_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON object containing relevant medical history'),
    sa.Column('insurance_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON object with insurance policy details'),
    sa.Column('parent_one_gender', sa.String(length=50), nullable=True, comment='Gender of the first parent/guardian'),
    sa.Column('parent_two_gender', sa.String(length=50), nullable=True, comment='Gender of the second parent/guardian'),
    sa.Column('parent_one_contact', sa.String(length=50), nullable=True, comment='Contact information for the first parent/guardian'),
    sa.Column('parent_two_contact', sa.String(length=50), nullable=True, comment='Contact information for the second parent/guardian'),
    sa.Column('family_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON object containing details about family members'),
    sa.Column('occupation', sa.String(length=255), nullable=True, comment="User's primary occupation"),
    sa.Column('designation', sa.String(length=255), nullable=True, comment="User's job title or designation"),
    sa.Column('department', sa.String(length=255), nullable=True, comment='Department the user belongs to'),
    sa.Column('education_qualification', sa.Text(), nullable=True, comment='Highest education qualification achieved'),
    sa.Column('education_specialization', sa.Text(), nullable=True, comment='Specialization within the education qualification'),
    sa.Column('education_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON array detailing educational background'),
    sa.Column('work_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON array detailing previous work experience'),
    sa.Column('reference_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON object containing professional or personal references'),
    sa.Column('referred_by_user_id', sa.BigInteger(), nullable=True, comment='User ID of the person who referred this user'),
    sa.Column('communication_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON object for communication channel preferences'),
    sa.Column('company_name', sa.String(length=255), nullable=True, comment='Name of the company the user is associated with'),
    sa.Column('company_address', sa.Text(), nullable=True, comment='Address of the associated company'),
    sa.Column('company_email', sa.String(length=255), nullable=True, comment='Email address of the associated company'),
    sa.Column('company_phone', sa.String(length=255), nullable=True, comment='Phone number of the associated company'),
    sa.Column('company_website', sa.String(length=255), nullable=True, comment='Website URL of the associated company'),
    sa.Column('company_gstin', sa.String(length=255), nullable=True, comment='GSTIN of the associated company'),
    sa.Column('company_pan', sa.String(length=255), nullable=True, comment='PAN of the associated company'),
    sa.Column('company_cin', sa.String(length=255), nullable=True, comment='CIN of the associated company'),
    sa.Column('company_tan', sa.String(length=255), nullable=True, comment='TAN of the associated company'),
    sa.Column('date_of_joining', sa.DateTime(timezone=True), nullable=True, comment='Date/time (with tz) when the user joined the company/platform'),
    sa.Column('member_id', sa.String(length=255), nullable=True, comment='Unique identifier for membership, if applicable'),
    sa.Column('current_sessions', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON data storing details about active user sessions'),
    sa.Column('has_active_session', sa.Boolean(), nullable=True, comment='Flag indicating if the user currently has an active session'),
    sa.Column('zoho_user_id', sa.String(length=255), nullable=True, comment='Unique identifier for the user in Zoho, if applicable'),
    sa.Column('onboarding_status', sa.String(length=255), nullable=True, comment="Status of the user's onboarding process"),
    sa.Column('image', sa.String(length=255), nullable=True, comment='Filename of the main profile picture'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='Filename of the avatar image'),
    sa.Column('thumbnail', sa.String(length=255), nullable=True, comment='Filename of the profile picture thumbnail'),
    sa.Column('preview_image', sa.String(length=255), nullable=True, comment='Filename of a preview-sized profile image'),
    sa.Column('profile_completion_percentage', sa.SmallInteger(), nullable=True, comment='Profile completion percentage (0-100)'),
    sa.Column('other_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON object for miscellaneous user details'),
    sa.Column('other_information', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON object for other structured information'),
    sa.Column('payment_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON object storing preferred payment methods or details'),
    sa.Column('bank_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON object storing bank account details'),
    sa.Column('billing_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON object representing the default billing address'),
    sa.Column('shipping_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON object representing the default shipping address'),
    sa.Column('language', sa.String(length=255), nullable=True, comment='Preferred language code'),
    sa.Column('timezone', sa.String(length=255), nullable=True, comment='Preferred timezone'),
    sa.Column('date_format', sa.String(length=255), nullable=True, comment='Preferred date format'),
    sa.Column('time_format', sa.String(length=255), nullable=True, comment='Preferred time format'),
    sa.Column('currency', sa.String(length=255), nullable=True, comment='Preferred currency code'),
    sa.Column('currency_symbol', sa.String(length=255), nullable=True, comment='Preferred currency symbol'),
    sa.Column('thousand_separator', sa.String(length=255), nullable=True, comment='Preferred thousand separator'),
    sa.Column('decimal_separator', sa.String(length=255), nullable=True, comment='Preferred decimal separator'),
    sa.Column('locale_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON object for detailed locale preferences'),
    sa.Column('online_status_preference', sa.SmallInteger(), nullable=True, comment='Online status display preference'),
    sa.Column('is_location_set', sa.Boolean(), nullable=True, comment='Whether the user explicitly set a primary location'),
    sa.Column('application_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON object for user-specific application settings'),
    sa.Column('default_language', sa.String(length=10), nullable=True, comment='Fallback or default language preference'),
    sa.Column('constituency', sa.String(length=255), nullable=True, comment='Name of the political constituency'),
    sa.Column('sub_constituency', sa.String(length=255), nullable=True, comment='Name of the sub-constituency'),
    sa.Column('assembly_constituency', sa.String(length=255), nullable=True, comment='Name of the assembly constituency'),
    sa.Column('parliamentary_constituency', sa.String(length=255), nullable=True, comment='Name of the parliamentary constituency'),
    sa.Column('pincode', sa.String(length=255), nullable=True, comment='Postal Index Number (PIN) code'),
    sa.Column('street_address', sa.Text(), nullable=True, comment="User's street address"),
    sa.Column('landmark', sa.String(length=255), nullable=True, comment='Nearby landmark for the address'),
    sa.Column('village_town', sa.String(length=255), nullable=True, comment='Name of the village or town'),
    sa.Column('taluka', sa.String(length=255), nullable=True, comment='Name of the taluka or sub-district'),
    sa.Column('district', sa.String(length=255), nullable=True, comment='Name of the district'),
    sa.Column('city', sa.String(length=255), nullable=True, comment='Name of the city'),
    sa.Column('state', sa.String(length=255), nullable=True, comment='Name of the state or province'),
    sa.Column('postal_code', sa.String(length=255), nullable=True, comment='Postal code'),
    sa.Column('country', sa.String(length=255), nullable=True, comment='Name of the country'),
    sa.Column('location', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True, comment='Primary geographic location (Point: lng, lat)'),
    sa.Column('current_location', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True, comment='Last known current geographic location'),
    sa.Column('route_points', Geography(geometry_type='LINESTRING', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True, comment='Series of geographic points representing a route'),
    sa.Column('constituency_geometry', Geography(srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True, comment='Geographic boundary of the constituency'),
    sa.Column('sub_constituency_geometry', Geography(srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True, comment='Geographic boundary of the sub-constituency'),
    sa.Column('assembly_constituency_geometry', Geography(srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True, comment='Geographic boundary of the assembly constituency'),
    sa.Column('parliamentary_constituency_geometry', Geography(srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True, comment='Geographic boundary of the parliamentary constituency'),
    sa.Column('pincode_geometry', Geography(srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True, comment='Geographic boundary corresponding to the pincode'),
    sa.Column('taluka_geometry', Geography(srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True, comment='Geographic boundary of the taluka'),
    sa.Column('district_geometry', Geography(srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True, comment='Geographic boundary of the district'),
    sa.Column('city_geometry', Geography(srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True, comment='Geographic boundary of the city'),
    sa.Column('state_geometry', Geography(srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True, comment='Geographic boundary of the state'),
    sa.Column('country_geometry', Geography(srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True, comment='Geographic boundary of the country'),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True, comment='Latitude coordinate'),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True, comment='Longitude coordinate'),
    sa.Column('coordinates', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True, comment='Alternative storage for geographic coordinates'),
    sa.Column('current_pincode', sa.String(length=20), nullable=True, comment='Pincode associated with the current location'),
    sa.Column('current_location_latitude', sa.String(length=255), nullable=True, comment='Latitude of the current location'),
    sa.Column('current_location_longitude', sa.String(length=255), nullable=True, comment='Longitude of the current location'),
    sa.Column('constituency_latitude', sa.Numeric(precision=10, scale=8), nullable=True, comment='Representative latitude for the constituency'),
    sa.Column('constituency_longitude', sa.Numeric(precision=11, scale=8), nullable=True, comment='Representative longitude for the constituency'),
    sa.Column('district_latitude', sa.Numeric(precision=10, scale=8), nullable=True, comment='Representative latitude for the district'),
    sa.Column('district_longitude', sa.Numeric(precision=11, scale=8), nullable=True, comment='Representative longitude for the district'),
    sa.Column('taluka_latitude', sa.Numeric(precision=10, scale=8), nullable=True, comment='Representative latitude for the taluka'),
    sa.Column('taluka_longitude', sa.Numeric(precision=11, scale=8), nullable=True, comment='Representative longitude for the taluka'),
    sa.Column('city_latitude', sa.Numeric(precision=10, scale=8), nullable=True, comment='Representative latitude for the city'),
    sa.Column('city_longitude', sa.Numeric(precision=11, scale=8), nullable=True, comment='Representative longitude for the city'),
    sa.Column('state_latitude', sa.Numeric(precision=10, scale=8), nullable=True, comment='Representative latitude for the state'),
    sa.Column('state_longitude', sa.Numeric(precision=11, scale=8), nullable=True, comment='Representative longitude for the state'),
    sa.Column('country_latitude', sa.Numeric(precision=10, scale=8), nullable=True, comment='Representative latitude for the country'),
    sa.Column('country_longitude', sa.Numeric(precision=11, scale=8), nullable=True, comment='Representative longitude for the country'),
    sa.Column('postal_code_latitude', sa.Numeric(precision=10, scale=8), nullable=True, comment='Representative latitude for the postal code area'),
    sa.Column('postal_code_longitude', sa.Numeric(precision=11, scale=8), nullable=True, comment='Representative longitude for the postal code area'),
    sa.Column('constituency_geonameId', sa.String(length=255), nullable=True, comment='GeoNames ID for the constituency'),
    sa.Column('sub_constituency_geonameId', sa.String(length=255), nullable=True, comment='GeoNames ID for the sub-constituency'),
    sa.Column('assembly_constituency_geonameId', sa.String(length=255), nullable=True, comment='GeoNames ID for the assembly constituency'),
    sa.Column('parliamentary_constituency_geonameId', sa.String(length=255), nullable=True, comment='GeoNames ID for the parliamentary constituency'),
    sa.Column('pincode_geonameId', sa.String(length=255), nullable=True, comment='GeoNames ID for the pincode area'),
    sa.Column('taluka_geonameId', sa.String(length=255), nullable=True, comment='GeoNames ID for the taluka'),
    sa.Column('district_geonameId', sa.String(length=255), nullable=True, comment='GeoNames ID for the district'),
    sa.Column('city_geonameId', sa.String(length=255), nullable=True, comment='GeoNames ID for the city'),
    sa.Column('state_geonameId', sa.String(length=255), nullable=True, comment='GeoNames ID for the state'),
    sa.Column('country_geonameId', sa.String(length=255), nullable=True, comment='GeoNames ID for the country'),
    sa.Column('altitude', sa.Numeric(precision=10, scale=8), nullable=True, comment='Altitude in meters above sea level'),
    sa.Column('altitude_accuracy', sa.Float(), nullable=True, comment='Accuracy of the altitude measurement in meters'),
    sa.Column('heading', sa.Float(), nullable=True, comment='Direction of travel in degrees (0-359.9)'),
    sa.Column('speed', sa.Float(), nullable=True, comment='Speed of travel in meters per second'),
    sa.Column('location_accuracy', sa.String(length=255), nullable=True, comment='Accuracy of the location measurement in meters'),
    sa.Column('location_source', sa.String(length=255), nullable=True, comment='Source of the location data (gps, network, manual)'),
    sa.Column('location_timestamp', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the location was recorded by the source'),
    sa.Column('location_timezone', sa.String(length=255), nullable=True, comment='Timezone detected at the location'),
    sa.Column('location_ip', sa.String(length=45), nullable=True, comment='IP address associated with the location capture event'),
    sa.Column('geocode', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON object containing reverse geocoding results'),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the location record was saved'),
    sa.Column('last_tracked_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of the very last tracking update received'),
    sa.Column('device_id', sa.String(length=255), nullable=True, comment='Identifier of the device providing tracking data'),
    sa.Column('device_type', sa.String(length=255), nullable=True, comment='Type of the device (mobile, web, sensor)'),
    sa.Column('network_type', sa.String(length=255), nullable=True, comment='Network type used during tracking (wifi, cellular)'),
    sa.Column('is_tracking_active', sa.Boolean(), nullable=True, comment='Whether location tracking is currently active'),
    sa.Column('background_tracking_enabled', sa.Boolean(), nullable=True, comment='Whether background location tracking is enabled'),
    sa.Column('external_id', sa.String(length=255), nullable=True, comment='Unique identifier for linking to an external system (Authentik sub / uuid)'),
    sa.Column('authentik_pk', sa.String(length=36), nullable=True, comment='Authentik admin-API user id (pk) for outbound sync'),
    sa.Column('authentik_sync_status', sa.String(length=50), nullable=True, comment='pending | synced | failed | password_drift | skipped'),
    sa.Column('authentik_sync_error', sa.Text(), nullable=True, comment='Last Authentik sync error (truncated)'),
    sa.Column('authentik_synced_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of the last successful Authentik sync'),
    sa.Column('zoho_id', sa.String(length=255), nullable=True, comment='Generic Zoho ID, if applicable'),
    sa.Column('zoho_customer_id', sa.String(length=255), nullable=True, comment='Zoho CRM Customer ID'),
    sa.Column('zoho_contact_id', sa.String(length=255), nullable=True, comment='Zoho CRM Contact ID'),
    sa.Column('targets', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON object for tracking user targets or goals'),
    sa.Column('target_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON object for tracking historical target data'),
    sa.Column('target_progress', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON object for tracking progress against targets'),
    sa.Column('target_achievements', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON object for tracking achievements against targets'),
    sa.Column('target_achievements_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON object for historical achievements against targets'),
    sa.Column('last_sync_time', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of the last data synchronization'),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of the last successful login'),
    sa.Column('last_password_change_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the password was last changed'),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True, comment='Count of consecutive failed login attempts'),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the account was locked due to failed attempts'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='ID of the user who created this record'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='ID of the user who last updated this record'),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True, comment='ID of the user who soft-deleted this record'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft-delete timestamp'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_token'),
    sa.UniqueConstraint('authentik_pk'),
    sa.UniqueConstraint('external_id'),
    sa.UniqueConstraint('username')
    )
    op.create_geospatial_index('idx_users_assembly_constituency_geometry', 'users', ['assembly_constituency_geometry'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_users_city_geometry', 'users', ['city_geometry'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_users_constituency_geometry', 'users', ['constituency_geometry'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_users_coordinates', 'users', ['coordinates'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_users_country_geometry', 'users', ['country_geometry'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_users_current_location', 'users', ['current_location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_users_district_geometry', 'users', ['district_geometry'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_users_location', 'users', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_users_parliamentary_constituency_geometry', 'users', ['parliamentary_constituency_geometry'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_users_pincode_geometry', 'users', ['pincode_geometry'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_users_route_points', 'users', ['route_points'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_users_state_geometry', 'users', ['state_geometry'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_users_sub_constituency_geometry', 'users', ['sub_constituency_geometry'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_users_taluka_geometry', 'users', ['taluka_geometry'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('users_authentik_sync_status_index', 'users', ['authentik_sync_status'], unique=False)
    op.create_index('users_city_index', 'users', ['city'], unique=False)
    op.create_index('users_company_name_index', 'users', ['company_name'], unique=False)
    op.create_index('users_country_index', 'users', ['country'], unique=False)
    op.create_index('users_created_by_index', 'users', ['created_by'], unique=False)
    op.create_index('users_deleted_at_index', 'users', ['deleted_at'], unique=False)
    op.create_index('users_deleted_by_index', 'users', ['deleted_by'], unique=False)
    op.create_index('users_device_id_index', 'users', ['device_id'], unique=False)
    op.create_index('users_first_last_name_index', 'users', ['first_name', 'last_name'], unique=False)
    op.create_index('users_last_login_index', 'users', ['last_login'], unique=False)
    op.create_index('users_last_tracked_at_index', 'users', ['last_tracked_at'], unique=False)
    op.create_index('users_member_id_index', 'users', ['member_id'], unique=False)
    op.create_index('users_phone_index', 'users', ['phone'], unique=False)
    op.create_index('users_pincode_index', 'users', ['pincode'], unique=False)
    op.create_index('users_role_id_index', 'users', ['role_id'], unique=False)
    op.create_index('users_state_index', 'users', ['state'], unique=False)
    op.create_index('users_status_index', 'users', ['status'], unique=False)
    op.create_index('users_updated_by_index', 'users', ['updated_by'], unique=False)
    op.create_index('users_user_type_index', 'users', ['user_type'], unique=False)
    op.create_index('users_zoho_contact_id_index', 'users', ['zoho_contact_id'], unique=False)
    op.create_index('users_zoho_customer_id_index', 'users', ['zoho_customer_id'], unique=False)
    op.create_index('users_zoho_id_index', 'users', ['zoho_id'], unique=False)
    op.create_table('zoho_sync_state',
    sa.Column('entity', sa.String(length=64), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.String(length=512), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('entity')
    )
    op.create_table('favorites',
    sa.Column('favorite_id', sa.UUID(), nullable=False, comment='Public UUID'),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('favoritable_type', sa.String(length=100), nullable=False),
    sa.Column('favoritable_id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True, comment='Display-name snapshot'),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False, comment='Manual ordering'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'favoritable_type', 'favoritable_id', name='uq_favorite_user_target')
    )
    op.create_index('ix_favorite_user_type', 'favorites', ['user_id', 'favoritable_type'], unique=False)
    op.create_index(op.f('ix_favorites_favoritable_id'), 'favorites', ['favoritable_id'], unique=False)
    op.create_index(op.f('ix_favorites_favoritable_type'), 'favorites', ['favoritable_type'], unique=False)
    op.create_index(op.f('ix_favorites_favorite_id'), 'favorites', ['favorite_id'], unique=True)
    op.create_index(op.f('ix_favorites_tenant_id'), 'favorites', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_favorites_user_id'), 'favorites', ['user_id'], unique=False)
    # NOTE: autogenerate had captured DROP TABLE layer/topology here — those
    # belong to the postgis_topology EXTENSION and must never be managed by
    # migrations (dropping them fails on any fresh database). Removed; env.py
    # now excludes them from autogenerate permanently.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favorites_user_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_tenant_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_favorite_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_favoritable_type'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_favoritable_id'), table_name='favorites')
    op.drop_index('ix_favorite_user_type', table_name='favorites')
    op.drop_table('favorites')
    op.drop_table('zoho_sync_state')
    op.drop_index('users_zoho_id_index', table_name='users')
    op.drop_index('users_zoho_customer_id_index', table_name='users')
    op.drop_index('users_zoho_contact_id_index', table_name='users')
    op.drop_index('users_user_type_index', table_name='users')
    op.drop_index('users_updated_by_index', table_name='users')
    op.drop_index('users_status_index', table_name='users')
    op.drop_index('users_state_index', table_name='users')
    op.drop_index('users_role_id_index', table_name='users')
    op.drop_index('users_pincode_index', table_name='users')
    op.drop_index('users_phone_index', table_name='users')
    op.drop_index('users_member_id_index', table_name='users')
    op.drop_index('users_last_tracked_at_index', table_name='users')
    op.drop_index('users_last_login_index', table_name='users')
    op.drop_index('users_first_last_name_index', table_name='users')
    op.drop_index('users_device_id_index', table_name='users')
    op.drop_index('users_deleted_by_index', table_name='users')
    op.drop_index('users_deleted_at_index', table_name='users')
    op.drop_index('users_created_by_index', table_name='users')
    op.drop_index('users_country_index', table_name='users')
    op.drop_index('users_company_name_index', table_name='users')
    op.drop_index('users_city_index', table_name='users')
    op.drop_index('users_authentik_sync_status_index', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_geospatial_index('idx_users_taluka_geometry', table_name='users', postgresql_using='gist', column_name='taluka_geometry')
    op.drop_geospatial_index('idx_users_sub_constituency_geometry', table_name='users', postgresql_using='gist', column_name='sub_constituency_geometry')
    op.drop_geospatial_index('idx_users_state_geometry', table_name='users', postgresql_using='gist', column_name='state_geometry')
    op.drop_geospatial_index('idx_users_route_points', table_name='users', postgresql_using='gist', column_name='route_points')
    op.drop_geospatial_index('idx_users_pincode_geometry', table_name='users', postgresql_using='gist', column_name='pincode_geometry')
    op.drop_geospatial_index('idx_users_parliamentary_constituency_geometry', table_name='users', postgresql_using='gist', column_name='parliamentary_constituency_geometry')
    op.drop_geospatial_index('idx_users_location', table_name='users', postgresql_using='gist', column_name='location')
    op.drop_geospatial_index('idx_users_district_geometry', table_name='users', postgresql_using='gist', column_name='district_geometry')
    op.drop_geospatial_index('idx_users_current_location', table_name='users', postgresql_using='gist', column_name='current_location')
    op.drop_geospatial_index('idx_users_country_geometry', table_name='users', postgresql_using='gist', column_name='country_geometry')
    op.drop_geospatial_index('idx_users_coordinates', table_name='users', postgresql_using='gist', column_name='coordinates')
    op.drop_geospatial_index('idx_users_constituency_geometry', table_name='users', postgresql_using='gist', column_name='constituency_geometry')
    op.drop_geospatial_index('idx_users_city_geometry', table_name='users', postgresql_using='gist', column_name='city_geometry')
    op.drop_geospatial_index('idx_users_assembly_constituency_geometry', table_name='users', postgresql_using='gist', column_name='assembly_constituency_geometry')
    op.drop_geospatial_table('users')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_files_zoho_id'), table_name='files')
    op.drop_index(op.f('ix_files_vendor_name'), table_name='files')
    op.drop_index(op.f('ix_files_uploaded_by'), table_name='files')
    op.drop_index(op.f('ix_files_tenant_id'), table_name='files')
    op.drop_index(op.f('ix_files_s3_key'), table_name='files')
    op.drop_index(op.f('ix_files_s3_bucket'), table_name='files')
    op.drop_index(op.f('ix_files_processing_status'), table_name='files')
    op.drop_index(op.f('ix_files_is_verified'), table_name='files')
    op.drop_index(op.f('ix_files_is_active'), table_name='files')
    op.drop_index(op.f('ix_files_fileable_type'), table_name='files')
    op.drop_index(op.f('ix_files_fileable_id'), table_name='files')
    op.drop_index(op.f('ix_files_file_type'), table_name='files')
    op.drop_index(op.f('ix_files_file_name'), table_name='files')
    op.drop_index(op.f('ix_files_file_id'), table_name='files')
    op.drop_index(op.f('ix_files_deleted_at'), table_name='files')
    op.drop_index('ix_file_type_processing_status', table_name='files')
    op.drop_index('ix_created_at_processing_status', table_name='files')
    op.drop_table('files')
    op.drop_index('ix_activity_tenant_created', table_name='activity_logs')
    op.drop_index('ix_activity_subject', table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_tenant_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_subject_type'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_subject_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_request_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_created_at'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_actor_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_activity_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_action'), table_name='activity_logs')
    op.drop_index('ix_activity_action_created', table_name='activity_logs')
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
