"""zoho currencies and taxes — the first O1 masters (Phase 5)

Mirror tables for GET /settings/currencies and GET /settings/taxes, built from
the split mixins (ZohoIdentityMixin + ZohoMirrorMixin) so the apply gate can
fence, hash and tombstone them from day one. Each has the partial unique
index on the live zoho_id that the registry validator requires.

Autogenerated, then trimmed: autogenerate also proposed the pre-existing,
unrelated users/countries/password-token drift, which is NOT part of this
change (see docs/zoho-sync-implementation/ERRORS-AND-THEIR-RESOLUTIONS.md E11).

Revision ID: 91e970e99176
Revises: f79d022c961a
Create Date: 2026-09-19
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '91e970e99176'
down_revision = 'f79d022c961a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table('zoho_currencies',
    sa.Column('currency_code', sa.String(length=100), nullable=True),
    sa.Column('currency_name', sa.String(length=255), nullable=True),
    sa.Column('currency_symbol', sa.String(length=16), nullable=True),
    sa.Column('currency_format', sa.String(length=100), nullable=True),
    sa.Column('price_precision', sa.Integer(), nullable=True),
    sa.Column('is_base_currency', sa.Boolean(), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('zoho_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Full untouched Zoho document'),
    sa.Column('zoho_raw_hash', sa.LargeBinary(), nullable=True, comment='sha256 of zoho_raw minus volatile keys (apply-gate no-op check)'),
    sa.Column('zoho_raw_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('zoho_last_modified_time', sa.DateTime(timezone=True), nullable=True, comment='Zoho version of the stored data (monotonic fence)'),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_source', sa.String(length=48), nullable=True, comment='Provenance of zoho_raw: list:<mode> | detail_fetch | nested:<parent> | webhook'),
    sa.Column('sync_version', sa.BigInteger(), server_default=sa.text('0'), nullable=False, comment='Incremented on every applied change'),
    sa.Column('remote_deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Tombstone evidence: when the sync learned Zoho deleted it'),
    sa.Column('custom_fields', postgresql.HSTORE(text_type=sa.Text()), nullable=True, comment='Zoho custom fields flattened to text (raw array in zoho_raw)'),
    sa.Column('zoho_id', sa.String(length=50), nullable=True, comment='Zoho primary key; NULL until first outbound push succeeds'),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=True, comment='Local stable id; correlation reference sent to Zoho'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index(op.f('ix_zoho_currencies_currency_code'), 'zoho_currencies', ['currency_code'], unique=False)
    op.create_index(op.f('ix_zoho_currencies_deleted_at'), 'zoho_currencies', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_zoho_currencies_zoho_id'), 'zoho_currencies', ['zoho_id'], unique=False)
    op.create_index(op.f('ix_zoho_currencies_zoho_last_modified_time'), 'zoho_currencies', ['zoho_last_modified_time'], unique=False)
    op.create_index('uq_zoho_currencies_zoho_id_live', 'zoho_currencies', ['zoho_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL AND zoho_id IS NOT NULL'))
    op.create_table('zoho_taxes',
    sa.Column('tax_name', sa.String(length=255), nullable=True),
    sa.Column('tax_percentage', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('tax_type', sa.String(length=32), nullable=True),
    sa.Column('tax_specific_type', sa.String(length=32), nullable=True),
    sa.Column('tax_factor', sa.String(length=16), nullable=True),
    sa.Column('tax_authority_id', sa.String(length=50), nullable=True),
    sa.Column('tax_authority_name', sa.String(length=255), nullable=True),
    sa.Column('is_value_added', sa.Boolean(), nullable=True),
    sa.Column('is_default_tax', sa.Boolean(), nullable=True),
    sa.Column('is_editable', sa.Boolean(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('country_code', sa.String(length=8), nullable=True),
    sa.Column('tax_account_id', sa.String(length=50), nullable=True),
    sa.Column('purchase_tax_account_id', sa.String(length=50), nullable=True),
    sa.Column('output_tax_account_name', sa.String(length=255), nullable=True),
    sa.Column('purchase_tax_account_name', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('zoho_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Full untouched Zoho document'),
    sa.Column('zoho_raw_hash', sa.LargeBinary(), nullable=True, comment='sha256 of zoho_raw minus volatile keys (apply-gate no-op check)'),
    sa.Column('zoho_raw_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('zoho_last_modified_time', sa.DateTime(timezone=True), nullable=True, comment='Zoho version of the stored data (monotonic fence)'),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_source', sa.String(length=48), nullable=True, comment='Provenance of zoho_raw: list:<mode> | detail_fetch | nested:<parent> | webhook'),
    sa.Column('sync_version', sa.BigInteger(), server_default=sa.text('0'), nullable=False, comment='Incremented on every applied change'),
    sa.Column('remote_deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Tombstone evidence: when the sync learned Zoho deleted it'),
    sa.Column('custom_fields', postgresql.HSTORE(text_type=sa.Text()), nullable=True, comment='Zoho custom fields flattened to text (raw array in zoho_raw)'),
    sa.Column('zoho_id', sa.String(length=50), nullable=True, comment='Zoho primary key; NULL until first outbound push succeeds'),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=True, comment='Local stable id; correlation reference sent to Zoho'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index(op.f('ix_zoho_taxes_deleted_at'), 'zoho_taxes', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_zoho_taxes_tax_name'), 'zoho_taxes', ['tax_name'], unique=False)
    op.create_index(op.f('ix_zoho_taxes_zoho_id'), 'zoho_taxes', ['zoho_id'], unique=False)
    op.create_index(op.f('ix_zoho_taxes_zoho_last_modified_time'), 'zoho_taxes', ['zoho_last_modified_time'], unique=False)
    op.create_index('uq_zoho_taxes_zoho_id_live', 'zoho_taxes', ['zoho_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL AND zoho_id IS NOT NULL'))


def downgrade() -> None:
    op.drop_index('uq_zoho_taxes_zoho_id_live', table_name='zoho_taxes', postgresql_where=sa.text('deleted_at IS NULL AND zoho_id IS NOT NULL'))
    op.drop_index(op.f('ix_zoho_taxes_zoho_last_modified_time'), table_name='zoho_taxes')
    op.drop_index(op.f('ix_zoho_taxes_zoho_id'), table_name='zoho_taxes')
    op.drop_index(op.f('ix_zoho_taxes_tax_name'), table_name='zoho_taxes')
    op.drop_index(op.f('ix_zoho_taxes_deleted_at'), table_name='zoho_taxes')
    op.drop_table('zoho_taxes')
    op.drop_index('uq_zoho_currencies_zoho_id_live', table_name='zoho_currencies', postgresql_where=sa.text('deleted_at IS NULL AND zoho_id IS NOT NULL'))
    op.drop_index(op.f('ix_zoho_currencies_zoho_last_modified_time'), table_name='zoho_currencies')
    op.drop_index(op.f('ix_zoho_currencies_zoho_id'), table_name='zoho_currencies')
    op.drop_index(op.f('ix_zoho_currencies_deleted_at'), table_name='zoho_currencies')
    op.drop_index(op.f('ix_zoho_currencies_currency_code'), table_name='zoho_currencies')
    op.drop_table('zoho_currencies')
