"""zoho locations and users — the remaining O1 masters (Phase 5)

zoho_locations (GET /locations — branches / warehouses) and zoho_users
(GET /users — the Zoho organization's users, NOT our accounts), both built
from ZohoIdentityMixin + ZohoMirrorMixin with the partial unique index on the
live zoho_id that the registry validator requires.

Autogenerated, then trimmed of the pre-existing unrelated users/countries/
password-token drift (ERRORS E11).

Revision ID: e6e42c16c52e
Revises: 91e970e99176
Create Date: 2026-09-19
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'e6e42c16c52e'
down_revision = '91e970e99176'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table('zoho_locations',
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('parent_location_id', sa.String(length=50), nullable=True),
    sa.Column('tax_settings_id', sa.String(length=50), nullable=True),
    sa.Column('auto_number_generation_id', sa.String(length=50), nullable=True),
    sa.Column('is_all_users_selected', sa.Boolean(), nullable=True),
    sa.Column('associated_series_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('associated_users', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('address_attention', sa.String(length=255), nullable=True),
    sa.Column('address_street1', sa.String(length=255), nullable=True),
    sa.Column('address_street2', sa.String(length=255), nullable=True),
    sa.Column('address_city', sa.String(length=100), nullable=True),
    sa.Column('address_state', sa.String(length=100), nullable=True),
    sa.Column('address_state_code', sa.String(length=10), nullable=True),
    sa.Column('address_country', sa.String(length=100), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('zoho_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Full untouched Zoho document'),
    sa.Column('zoho_raw_hash', sa.LargeBinary(), nullable=True, comment='sha256 of zoho_raw minus volatile keys (apply-gate no-op check)'),
    sa.Column('zoho_raw_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('zoho_last_modified_time', sa.DateTime(timezone=True), nullable=True, comment='Zoho version of the stored data (monotonic fence)'),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_source', sa.String(length=48), nullable=True, comment='Provenance of zoho_raw: list:<mode> | detail_fetch | nested:<parent> | webhook'),
    sa.Column('sync_version', sa.BigInteger(), server_default=sa.text('0'), nullable=False, comment='Incremented on every applied change'),
    sa.Column('remote_deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Tombstone evidence: when the sync learned Zoho deleted it'),
    sa.Column('custom_fields', postgresql.HSTORE(text_type=sa.Text()), nullable=True, comment='Zoho custom fields flattened to text (raw array in zoho_raw)'),
    sa.Column('zoho_id', sa.String(length=50), nullable=True, comment='Zoho primary key; NULL until first outbound push succeeds'),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=True, comment='Local stable id; correlation reference sent to Zoho'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index(op.f('ix_zoho_locations_deleted_at'), 'zoho_locations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_zoho_locations_location_name'), 'zoho_locations', ['location_name'], unique=False)
    op.create_index(op.f('ix_zoho_locations_parent_location_id'), 'zoho_locations', ['parent_location_id'], unique=False)
    op.create_index(op.f('ix_zoho_locations_status'), 'zoho_locations', ['status'], unique=False)
    op.create_index(op.f('ix_zoho_locations_zoho_id'), 'zoho_locations', ['zoho_id'], unique=False)
    op.create_index(op.f('ix_zoho_locations_zoho_last_modified_time'), 'zoho_locations', ['zoho_last_modified_time'], unique=False)
    op.create_index('uq_zoho_locations_zoho_id_live', 'zoho_locations', ['zoho_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL AND zoho_id IS NOT NULL'))
    op.create_table('zoho_users',
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('user_role', sa.String(length=100), nullable=True),
    sa.Column('role_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('user_type', sa.String(length=50), nullable=True),
    sa.Column('is_current_user', sa.Boolean(), nullable=True),
    sa.Column('is_customer_segmented', sa.Boolean(), nullable=True),
    sa.Column('is_vendor_segmented', sa.Boolean(), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('cost_rate', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('zoho_created_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('zoho_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Full untouched Zoho document'),
    sa.Column('zoho_raw_hash', sa.LargeBinary(), nullable=True, comment='sha256 of zoho_raw minus volatile keys (apply-gate no-op check)'),
    sa.Column('zoho_raw_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('zoho_last_modified_time', sa.DateTime(timezone=True), nullable=True, comment='Zoho version of the stored data (monotonic fence)'),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_source', sa.String(length=48), nullable=True, comment='Provenance of zoho_raw: list:<mode> | detail_fetch | nested:<parent> | webhook'),
    sa.Column('sync_version', sa.BigInteger(), server_default=sa.text('0'), nullable=False, comment='Incremented on every applied change'),
    sa.Column('remote_deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Tombstone evidence: when the sync learned Zoho deleted it'),
    sa.Column('custom_fields', postgresql.HSTORE(text_type=sa.Text()), nullable=True, comment='Zoho custom fields flattened to text (raw array in zoho_raw)'),
    sa.Column('zoho_id', sa.String(length=50), nullable=True, comment='Zoho primary key; NULL until first outbound push succeeds'),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=True, comment='Local stable id; correlation reference sent to Zoho'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index(op.f('ix_zoho_users_deleted_at'), 'zoho_users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_zoho_users_email'), 'zoho_users', ['email'], unique=False)
    op.create_index(op.f('ix_zoho_users_name'), 'zoho_users', ['name'], unique=False)
    op.create_index(op.f('ix_zoho_users_status'), 'zoho_users', ['status'], unique=False)
    op.create_index(op.f('ix_zoho_users_zoho_id'), 'zoho_users', ['zoho_id'], unique=False)
    op.create_index(op.f('ix_zoho_users_zoho_last_modified_time'), 'zoho_users', ['zoho_last_modified_time'], unique=False)
    op.create_index('uq_zoho_users_zoho_id_live', 'zoho_users', ['zoho_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL AND zoho_id IS NOT NULL'))


def downgrade() -> None:
    op.drop_index('uq_zoho_users_zoho_id_live', table_name='zoho_users', postgresql_where=sa.text('deleted_at IS NULL AND zoho_id IS NOT NULL'))
    op.drop_index(op.f('ix_zoho_users_zoho_last_modified_time'), table_name='zoho_users')
    op.drop_index(op.f('ix_zoho_users_zoho_id'), table_name='zoho_users')
    op.drop_index(op.f('ix_zoho_users_status'), table_name='zoho_users')
    op.drop_index(op.f('ix_zoho_users_name'), table_name='zoho_users')
    op.drop_index(op.f('ix_zoho_users_email'), table_name='zoho_users')
    op.drop_index(op.f('ix_zoho_users_deleted_at'), table_name='zoho_users')
    op.drop_table('zoho_users')
    op.drop_index('uq_zoho_locations_zoho_id_live', table_name='zoho_locations', postgresql_where=sa.text('deleted_at IS NULL AND zoho_id IS NOT NULL'))
    op.drop_index(op.f('ix_zoho_locations_zoho_last_modified_time'), table_name='zoho_locations')
    op.drop_index(op.f('ix_zoho_locations_zoho_id'), table_name='zoho_locations')
    op.drop_index(op.f('ix_zoho_locations_status'), table_name='zoho_locations')
    op.drop_index(op.f('ix_zoho_locations_parent_location_id'), table_name='zoho_locations')
    op.drop_index(op.f('ix_zoho_locations_location_name'), table_name='zoho_locations')
    op.drop_index(op.f('ix_zoho_locations_deleted_at'), table_name='zoho_locations')
    op.drop_table('zoho_locations')
